import type { Senaryo } from './tipler';

/* ═══════════════════════════════════════════════════════════════════════
   TERS KAPSAMA SENARYOLARI

   Bu dosyadaki senaryolar bir denetimden değil, bir ARACIN bulgusundan
   doğdu. `arac/ters-kapsam.mjs` kaynak koddan kullanıcı davranışı
   envanteri çıkarır ve kütükle karşılaştırır. İlk koşusunda 56 davranış
   "kütükte hiç yazılmamış" çıktı: dokuz rota, yirmi bir sunucu eylemi,
   beş motor, bir kuyruk girişi ve yalnız mutlu yol senaryosu taşıdığı
   için bozuk veri hâli hiç düşünülmemiş yirmi arayüz etkileşimi.

   Senaryo → test kapısı bu boşluğu göremezdi: OLMAYAN senaryonun testi
   de yoktur, kütük yine "GAP 0" derdi. Bu dosya o boşluğun kapanışıdır.

   Her senaryonun testi `tests/ters-kapsam-*.test.ts` içindedir ve
   senaryo kimliği testin başlığında geçer.
   ═══════════════════════════════════════════════════════════════════ */

/* ── Rotalar · kütükte hiç yazılmamış dokuz ekran ──────────────────── */

export const KAPSAMA_SENARYOLARI: Senaryo[] = [
  {
    id: 'SAH-GRS-001', alan: 'Saha', rota: '/', eksen: 'veri',
    amac: 'Santralleri fotoğrafıyla tanımak',
    rol: 'herhangi bir kullanıcı', kapsam: 'kendi kapsamı',
    onkosul: 'Bazı santralin fotoğrafı yok', veriHali: 'kısmi',
    eylem: 'Saha ekranını açar',
    beklenenSonuc: 'Fotoğrafı olmayan santral BAŞKA santralin görselini almaz',
    beklenenEkran: 'Tipografik geri düşüş; görsel ödünç alınmaz',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'UI'],
  },
  {
    id: 'SAH-GRS-002', alan: 'Saha', rota: '/', eksen: 'veri',
    amac: 'Uyum eğilimini görmek',
    rol: 'herhangi bir kullanıcı', kapsam: 'kendi kapsamı',
    onkosul: 'Hiç anlık görüntü alınmamış', veriHali: 'yok',
    eylem: 'Saha ekranını açar',
    beklenenSonuc: 'Eğilim şeridi null kalır — düz sıfır çizgisi ÇİZİLMEZ',
    beklenenEkran: '"Ölçülmedi" yazılır; eğilim uydurulmaz',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'DOMAIN'],
  },
  {
    id: 'AKT-IZL-001', alan: 'Aktivite', rota: '/aktivite', eksen: 'veri',
    amac: 'Belirli bir eylem türünü izlemek',
    rol: 'güvenlik denetçisi', kapsam: 'kurum geneli',
    onkosul: 'Seçilen mercek hiçbir kayda uymuyor', veriHali: 'yok',
    eylem: 'Mercek süzgecini uygular',
    beklenenSonuc: 'Boş SÜZGEÇ sonucu, hiç kayıt olmamasından ayrı yazılır',
    beklenenEkran: 'Süzgeci temizle eylemi görünür',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'UI'],
  },
  {
    id: 'AKT-IZL-002', alan: 'Aktivite', rota: '/aktivite', eksen: 'veri',
    amac: 'İzdeki aktör sayısını doğru okumak',
    rol: 'güvenlik denetçisi', kapsam: 'kurum geneli',
    onkosul: 'Bazı panel kaydının aktörü bilinmiyor', veriHali: 'kısmi',
    eylem: 'Metrik bandını okur',
    beklenenSonuc: 'Aktörü bilinmeyen kayıt ayrı sayılır; aktör sayısına katılmaz',
    beklenenEkran: 'Aktörsüz kayıt sayısı ayrı metrik',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN'],
  },
  {
    id: 'API-SZL-001', alan: 'API', rota: '/api-sozlesmesi', eksen: 'yetki',
    amac: 'Hangi anahtarın neye eriştiğini görmek',
    rol: 'güvenlik denetçisi', kapsam: 'kurum geneli',
    onkosul: 'Aktif anahtarların bazısının kapsamı tanımsız', veriHali: 'kısmi',
    eylem: 'Sözleşme ekranının özet cümlesini okur',
    beklenenSonuc: 'Kapsamı tanımsız anahtar ÖNCE söylenir; "hepsi salt okunur" cümlesi onu gizleyemez',
    beklenenEkran: 'Hiç anahtarın erişmediği uç bilinmeyen işaretiyle durur',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'UI'],
  },
  {
    id: 'SIS-BKM-001', alan: 'Sistem', rota: '/bakim', eksen: 'arayuz',
    amac: 'Bakım sırasında ne olduğunu anlamak',
    rol: 'herhangi bir ziyaretçi', kapsam: 'yok',
    onkosul: 'Bakım bitiş saati bilinmiyor', veriHali: 'bilinmiyor',
    eylem: 'Bakım ekranını açar',
    beklenenSonuc: 'Bitiş saati bilinmiyorsa "bilinmiyor" yazılır; süre TAHMİN EDİLMEZ',
    beklenenEkran: 'Kayıt okumaz; oturum istemez',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'UI'],
  },
  {
    id: 'SIS-TKN-001', alan: 'Sistem', rota: '/sistem', eksen: 'veri',
    amac: 'Tasarım token değerlerinin gerçeğini görmek',
    rol: 'tasarımcı / geliştirici', kapsam: 'kurum geneli',
    onkosul: 'Token değerleri stil dosyasında', veriHali: 'normal',
    eylem: 'Tasarım sistemi ekranını açar',
    beklenenSonuc: 'Değerler `app/kabuk.css` OKUNARAK gelir; ekranda elle yazılmış renk yoktur',
    beklenenEkran: 'Kaynak tek — ekran stil dosyasından ayrışamaz',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'VISUAL'],
  },
  {
    id: 'SIS-BLS-001', alan: 'Sistem', rota: '/sistem/bilesenler', eksen: 'arayuz',
    amac: 'Bozuk durum primitiflerini tek yerde görmek',
    rol: 'tasarımcı / geliştirici', kapsam: 'kurum geneli',
    onkosul: 'Galeri bileşen kütüğü', veriHali: 'yok',
    eylem: 'Bileşen galerisini açar',
    beklenenSonuc: 'Boş · ölçülmedi · bağlı değil · kısmi · hata durumlarının HEPSİ galeride yer alır',
    beklenenEkran: 'Ekranlar bozuk durumu tutarsız çizemez',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['UI', 'VISUAL'],
  },
  {
    id: 'UYU-SRC-001', alan: 'Uyum', rota: '/surecler', eksen: 'veri',
    amac: 'Sürecin uyum durumunu okumak',
    rol: 'uyum uzmanı', kapsam: 'kendi santrali',
    onkosul: 'Hiçbir madde değerlendirilmemiş', veriHali: 'yok',
    eylem: 'Süreç listesini açar',
    beklenenSonuc: 'Yüzde null kalır — %0 GÖSTERİLMEZ',
    beklenenEkran: '"Ölçülmedi" yazılır',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN'],
  },
  {
    id: 'UYU-SRC-002', alan: 'Uyum', rota: '/surecler', eksen: 'veri',
    amac: 'Süreç toplamını doğru okumak',
    rol: 'uyum uzmanı', kapsam: 'kendi santrali',
    onkosul: 'Bazı maddeler kapsam dışı', veriHali: 'kısmi',
    eylem: 'Süreç toplamına bakar',
    beklenenSonuc: 'Kapsam dışı maddeler paydaya GİRMEZ; toplam alt sayımların toplamıdır',
    beklenenEkran: 'Kapsam dışı ayrı sayılır',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN'],
  },
  {
    id: 'TES-YON-001', alan: 'Tesis', rota: '/tesisler', eksen: 'arayuz',
    amac: 'Eski bir adresten santral listesine ulaşmak',
    rol: 'herhangi bir kullanıcı', kapsam: 'kendi kapsamı',
    onkosul: 'Eski adres yer imlerinde', veriHali: 'yok',
    eylem: '/tesisler adresini açar',
    beklenenSonuc: 'Kanon listeye yönlendirilir; derin bağ kırılmaz',
    beklenenEkran: 'İki ayrı santral listesi tutulmaz',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['UI'],
  },
  {
    id: 'DEN-LST-002', alan: 'Denetim', rota: '/denetimler', eksen: 'veri',
    amac: 'Planlı denetim olup olmadığını görmek',
    rol: 'uyum yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Kapsamda hiç denetim planlanmamış', veriHali: 'yok',
    eylem: 'Denetimler ekranını açar',
    beklenenSonuc: 'Boş liste "denetlendi ve temiz" ile KARIŞTIRILMAZ',
    beklenenEkran: 'Boş ilk-durum; süzgeç boşluğundan ayrı',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'UI'],
  },
  {
    id: 'UYU-CRC-004', alan: 'Uyum', rota: '/uyum/[cerceve]', eksen: 'veri',
    amac: 'Çerçevenin madde başına durumunu görmek',
    rol: 'uyum uzmanı', kapsam: 'kendi santrali',
    onkosul: 'Çerçevenin bazı maddeleri hiç değerlendirilmemiş', veriHali: 'kısmi',
    eylem: 'Madde satırını genişletir',
    beklenenSonuc: 'Değerlendirilmemiş madde "uyumlu" ya da "uyumsuz" SAYILMAZ',
    beklenenEkran: 'Genişleyen satırda "ölçülmedi" ayrı okunur',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'UI'],
  },
  {
    id: 'YON-TZG-001', alan: 'Yönetim konsolu', rota: '/yonetim-tezgahi', eksen: 'veri',
    amac: 'Kendine düşen işi bulmak',
    rol: 'herhangi bir kullanıcı', kapsam: 'kendi kapsamı',
    onkosul: 'Süzgeç hiçbir göreve uymuyor', veriHali: 'yok',
    eylem: 'Görev süzgecini daraltır',
    beklenenSonuc: 'Boş SÜZGEÇ sonucu, hiç görev olmamasından ayrı yazılır',
    beklenenEkran: 'Süzgeci temizle eylemi görünür',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'UI'],
  },

  /* ── Sunucu eylemleri · kütükte hiç yazılmamış yirmi bir giriş ────── */

  {
    id: 'OLY-BLD-001', alan: 'Olay', rota: '/olaylar', eksen: 'akis',
    amac: 'Yürürlükten kalkmış bildirim kuralını kaldırmak',
    rol: 'uyum yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Kural geçmiş olaylarda kullanılmış', veriHali: 'normal',
    eylem: 'Bildirim kuralını siler',
    beklenenSonuc: 'Kayıt SİLİNMEZ, pasifleştirilir — geçmiş olayın hangi kurala göre değerlendirildiği kalır',
    beklenenEkran: 'Kural pasif olarak görünür',
    beklenenIz: 'BildirimYukumlulugu · guncelleme (aktif: true→false)', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'WORKFLOW'],
  },
  {
    id: 'EGT-MDD-001', alan: 'Eğitim', rota: '/egitimler', eksen: 'akis',
    amac: 'Yanlış bağlanmış eğitim–madde bağını kaldırmak',
    rol: 'uyum yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Bağ zaten kaldırılmış', veriHali: 'yok',
    eylem: 'Aynı bağı ikinci kez kaldırır',
    beklenenSonuc: 'İkinci çağrı hata vermez ve İZ YAZMAZ — idempotent',
    beklenenEkran: 'Ekran değişmez',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER'],
  },
  {
    id: 'SAG-KOS-001', alan: 'Sağlık', rota: '/saglik', eksen: 'entegrasyon',
    amac: 'Kaynağı yazmadan denemek',
    rol: 'BT yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Connector tanımlı', veriHali: 'normal',
    eylem: 'Kuru koşu başlatır',
    beklenenSonuc: 'Hiçbir kayıt YAZILMAZ; yalnız koşu özeti ve iz üretilir',
    beklenenEkran: 'Kuru koşu ayrı işaretlenir',
    beklenenIz: 'Connector · kuru_kosu', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'INTEGRATION'],
  },
  {
    id: 'SAG-KOS-002', alan: 'Sağlık', rota: '/saglik', eksen: 'entegrasyon',
    amac: 'Senkronizasyonu elle tetiklemek',
    rol: 'BT yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Tetikleyen değeri sözlükte yok', veriHali: 'çelişen',
    eylem: 'Tanımsız bir tetikleyen adıyla senkronizasyon çağırır',
    beklenenSonuc: 'Reddedilir; koşu AÇILMAZ',
    beklenenEkran: 'Hata cümlesi tetikleyeni adlandırır',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'INTEGRATION'],
  },
  {
    id: 'SAG-ETK-001', alan: 'Sağlık', rota: '/saglik', eksen: 'entegrasyon',
    amac: 'Kaynağı etkinleştirmek',
    rol: 'BT yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Connector kimlik ister ama sır referansı tanımsız', veriHali: 'kısmi',
    eylem: 'Connector\'ı etkinleştirmeyi dener',
    beklenenSonuc: 'Reddedilir — sır referansı olmadan etkinleştirilemez',
    beklenenEkran: 'Eksik olanın ne olduğu yazılır',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'INTEGRATION'],
  },
  {
    id: 'ESL-SZL-001', alan: 'Eşleme', rota: '/esleme', eksen: 'veri',
    amac: 'Hedef alanları ve dönüşümleri görmek',
    rol: 'entegrasyon uzmanı', kapsam: 'kurum geneli',
    onkosul: 'Eşleme tezgâhı açık', veriHali: 'normal',
    eylem: 'Alan sözlüğünü okur',
    beklenenSonuc: 'Sözlük hedef alanların KOPYASINI verir; çağıran onu değiştirerek kaynağı bozamaz',
    beklenenEkran: 'Alan listesi tek kaynaktan',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'DOMAIN'],
  },
  {
    id: 'ESL-BAG-001', alan: 'Eşleme', rota: '/esleme', eksen: 'entegrasyon',
    amac: 'Kaynağa eşleme profili bağlamak',
    rol: 'entegrasyon uzmanı', kapsam: 'kurum geneli',
    onkosul: 'Profil başka connector tipi için yazılmış', veriHali: 'çelişen',
    eylem: 'Tipi tutmayan profili bağlamayı dener',
    beklenenSonuc: 'Reddedilir — yükte hiçbir alan bulunamayacağı için kayıtlar sessizce boş geçerdi',
    beklenenEkran: 'Hata iki tipi de adlandırır',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'INTEGRATION'],
  },
  {
    id: 'GZD-KRR-001', alan: 'Gözden geçirme', rota: '/gozden-gecirme', eksen: 'akis',
    amac: 'Gözden geçirme kararını kapatmak',
    rol: 'uyum yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Karara bağlı görev açık', veriHali: 'normal',
    eylem: 'Kararı tamamlandı olarak işaretler',
    beklenenSonuc: 'Bağlı görev de kapanır — iş iki yerde ayrı ayrı kapatılmaz',
    beklenenEkran: 'Görev kuyruğunda kalmaz',
    beklenenIz: 'GozdenGecirmeKarari · guncelleme (durum)', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'WORKFLOW'],
  },
  {
    id: 'GZD-KRR-002', alan: 'Gözden geçirme', rota: '/gozden-gecirme', eksen: 'akis',
    amac: 'Gözden geçirme kararını iptal etmek',
    rol: 'uyum yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Gerekçe girilmemiş', veriHali: 'kısmi',
    eylem: 'Kararı gerekçesiz iptal etmeyi dener',
    beklenenSonuc: 'Reddedilir — iptal gerekçe ister',
    beklenenEkran: 'Eksik alan adlandırılır',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'WORKFLOW'],
  },
  {
    id: 'OLY-ETK-003', alan: 'Olay', rota: '/olaylar', eksen: 'yetki',
    amac: 'Olayın etki önerisini tazelemek',
    rol: 'santral kullanıcısı', kapsam: 'tek santral',
    onkosul: 'Olay başka santralde', veriHali: 'normal',
    eylem: 'Kapsam dışı olayın etki önerisini yenilemeyi dener',
    beklenenSonuc: 'Reddedilir; hiçbir öneri yazılmaz',
    beklenenEkran: 'Yetki cümlesi',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'SCOPE'],
  },
  {
    id: 'TOP-TML-001', alan: 'Topoloji', rota: '/topoloji', eksen: 'yetki',
    amac: 'Bir anlığı yürürlükteki temel yapmak',
    rol: 'santral kullanıcısı', kapsam: 'tek santral',
    onkosul: 'Anlık başka santralin', veriHali: 'normal',
    eylem: 'Kapsam dışı anlığı temel onaylamayı dener',
    beklenenSonuc: 'Reddedilir; yürürlükteki temel DEĞİŞMEZ',
    beklenenEkran: 'Yetki cümlesi tesisi adlandırır',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'SCOPE'],
  },
  {
    id: 'TOP-BUL-001', alan: 'Topoloji', rota: '/topoloji', eksen: 'akis',
    amac: 'Sapmadan bulgu açmak',
    rol: 'uyum uzmanı', kapsam: 'kendi santrali',
    onkosul: 'Madde durumu seçilmemiş', veriHali: 'kısmi',
    eylem: 'Madde durumu bağlamadan bulgu açmayı dener',
    beklenenSonuc: 'Reddedilir — bağsız bulgu hangi maddeyi ihlal ettiğini söyleyemez',
    beklenenEkran: 'Eksik alan adlandırılır',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'WORKFLOW'],
  },
  {
    id: 'VAK-YUK-001', alan: 'Varlık aktarımı', rota: '/varlik-aktarim', eksen: 'akis',
    amac: 'Varlık listesini dosyadan aktarmak',
    rol: 'BT yöneticisi', kapsam: 'kendi santrali',
    onkosul: 'Dosya desteklenmeyen türde', veriHali: 'çelişen',
    eylem: 'Desteklenmeyen uzantılı dosya yükler',
    beklenenSonuc: 'Reddedilir; aktarım kaydı AÇILMAZ',
    beklenenEkran: 'Hata uzantıyı adlandırır',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'INTEGRATION'],
  },
  {
    id: 'VAK-ESL-001', alan: 'Varlık aktarımı', rota: '/varlik-aktarim', eksen: 'akis',
    amac: 'Kaynak sütunlarını hedef alanlara eşlemek',
    rol: 'BT yöneticisi', kapsam: 'kendi santrali',
    onkosul: 'Zorunlu hedef alan eşlenmemiş', veriHali: 'kısmi',
    eylem: 'Eksik eşlemeyle ilerlemeyi dener',
    beklenenSonuc: 'Reddedilir; eksik alan adlandırılır',
    beklenenEkran: 'Aşama hattı eşleşme adımında kalır',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'WORKFLOW'],
  },
  {
    id: 'VAK-RED-001', alan: 'Varlık aktarımı', rota: '/varlik-aktarim', eksen: 'akis',
    amac: 'Hatalı aktarımı reddetmek',
    rol: 'BT yöneticisi', kapsam: 'kendi santrali',
    onkosul: 'Aktarım zaten onaylanmış', veriHali: 'normal',
    eylem: 'Onaylanmış aktarımı reddetmeyi dener',
    beklenenSonuc: 'Reddedilir — karara bağlanmış aktarım yeniden karara açılmaz',
    beklenenEkran: 'Durum değişmez',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'WORKFLOW'],
  },
  {
    id: 'ENV-UYG-001', alan: 'Envanter', rota: '/envanter', eksen: 'yetki',
    amac: 'Bir alanın uygulanamaz işaretini kaldırmak',
    rol: 'santral kullanıcısı', kapsam: 'tek santral',
    onkosul: 'Varlık başka santralde', veriHali: 'normal',
    eylem: 'Kapsam dışı varlığın işaretini kaldırmayı dener',
    beklenenSonuc: 'Reddedilir; işaret DURUR',
    beklenenEkran: 'Yetki cümlesi',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'SCOPE'],
  },
  {
    id: 'ENV-FRM-010', alan: 'Envanter', rota: '/envanter', eksen: 'akis',
    amac: 'Yükseltilemeyen firmware için istisna kaydetmek',
    rol: 'BT yöneticisi', kapsam: 'kendi santrali',
    onkosul: 'Cihaz eski firmware\'de', veriHali: 'normal',
    eylem: 'İstisna gerekçesini kaydeder',
    beklenenSonuc: 'Uyum DURUMU DEĞİŞMEZ — cihaz hâlâ eski sürümdedir; istisna yalnız "biliniyor ve kabul edildi" der',
    beklenenEkran: 'İstisna rozeti; durum rengi aynı kalır',
    beklenenIz: 'Varlik · onay (firmwareIstisnasi)', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'DOMAIN'],
  },
  {
    id: 'ENV-PRS-001', alan: 'Envanter', rota: '/prosesler', eksen: 'yetki',
    amac: 'Yanlış bağlanmış proses adımı bağını kaldırmak',
    rol: 'santral kullanıcısı', kapsam: 'tek santral',
    onkosul: 'Bağın varlığı başka santralde', veriHali: 'normal',
    eylem: 'Kapsam dışı bağı kaldırmayı dener',
    beklenenSonuc: 'Reddedilir; bağ DURUR',
    beklenenEkran: 'Yetki cümlesi',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'SCOPE'],
  },
  {
    id: 'YTK-EKP-001', alan: 'Yetkiler', rota: '/yetkiler', eksen: 'akis',
    amac: 'Ekipten ayrılan kişiyi çıkarmak',
    rol: 'kurum yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Üyelik zaten yok', veriHali: 'yok',
    eylem: 'Olmayan üyeliği kaldırmayı dener',
    beklenenSonuc: 'Hata döner; sessizce başarılı SAYILMAZ',
    beklenenEkran: 'Ekip listesi değişmez',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER'],
  },
  {
    id: 'YDP-BAG-001', alan: 'Yedek parça', rota: '/yedek-parca', eksen: 'yetki',
    amac: 'Parça–varlık bağını çözmek',
    rol: 'santral kullanıcısı', kapsam: 'tek santral',
    onkosul: 'Bağın varlığı başka santralde', veriHali: 'normal',
    eylem: 'Kapsam dışı bağı çözmeyi dener',
    beklenenSonuc: 'Reddedilir; bağ DURUR',
    beklenenEkran: 'Yetki cümlesi',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'SCOPE'],
  },
  {
    id: 'YON-MOD-003', alan: 'Yönetim konsolu', rota: '/ayarlar', eksen: 'veri',
    amac: 'Bir modülün sınıfını öğrenmek',
    rol: 'kurum yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Kod kütükte yok', veriHali: 'bilinmiyor',
    eylem: 'Tanımsız modül kodunu sorar',
    beklenenSonuc: 'null döner — varsayılan bir sınıfa DÜŞMEZ',
    beklenenEkran: '"Bilinmiyor" yazılır',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'DOMAIN'],
  },
  {
    id: 'ZIM-SUR-010', alan: 'Zimmet', rota: '/zimmetlerim', eksen: 'veri',
    amac: 'Zimmet süresinin sınırını bilmek',
    rol: 'herhangi bir kullanıcı', kapsam: 'kendi kapsamı',
    onkosul: 'Zimmet formu açık', veriHali: 'normal',
    eylem: 'Süre alanını doldurur',
    beklenenSonuc: 'Varsayılan ve azami gün TEK kaynaktan gelir; ekran kendi sayısını uydurmaz',
    beklenenEkran: 'Azami gün alan ipucunda yazılı',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'DOMAIN'],
  },

  /* ── Motorlar · kütükte hiç yazılmamış beş koşu ───────────────────── */

  {
    id: 'UYU-ANL-001', alan: 'Uyum', rota: '—', eksen: 'akis',
    amac: 'Uyum duruşunun günlük anlık görüntüsünü almak',
    rol: 'sistem (motor)', kapsam: 'kurum geneli',
    onkosul: 'Aynı gün zaten anlık alınmış', veriHali: 'yinelenen',
    eylem: 'Motor aynı gün ikinci kez koşar',
    beklenenSonuc: 'İkinci anlık YAZILMAZ — günde bir',
    beklenenEkran: '—',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['ENGINE'],
  },
  {
    id: 'ENV-FRM-011', alan: 'Envanter', rota: '—', eksen: 'akis',
    amac: 'Firmware uyumunu hesaplamak',
    rol: 'sistem (motor)', kapsam: 'kurum geneli',
    onkosul: 'Karar önceki koşuyla aynı', veriHali: 'yinelenen',
    eylem: 'Motor tekrar koşar',
    beklenenSonuc: 'Aynı karar YENİDEN YAZILMAZ — "bu karar ne zaman değişti" sorusu cevapsız kalmasın',
    beklenenEkran: '—',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['ENGINE'],
  },
  {
    id: 'ENV-AGT-001', alan: 'Envanter', rota: '—', eksen: 'veri',
    amac: 'Ağ tutarlılığını denetlemek',
    rol: 'sistem (motor)', kapsam: 'kurum geneli',
    onkosul: 'Bazı varlığın IP adresi ölçülmemiş', veriHali: 'bilinmiyor',
    eylem: 'Motor koşar',
    beklenenSonuc: 'Ölçüm borcu AYRI bir kural adıyla yazılır — "ölçemedik" ile "sorun yok" aynı sayılmaz',
    beklenenEkran: '—',
    beklenenIz: 'VeriKalitesiBulgusu · olusturma (…_olculemedi)', beklenenBildirim: 'yok',
    katmanlar: ['ENGINE'],
  },
  {
    id: 'TAB-DRF-001', alan: 'Konfigürasyon tabanı', rota: '/tabanlar', eksen: 'veri',
    amac: 'Konfigürasyon sapmasını görmek',
    rol: 'sistem (motor)', kapsam: 'kurum geneli',
    onkosul: 'Yedeğin içerik özeti yok', veriHali: 'bilinmiyor',
    eylem: 'Motor koşar',
    beklenenSonuc: 'Karar verilemeyen durum sapma AÇMAZ — özet hesaplayamayan bir kaynak bütün filoyu kırmızıya boyamaz',
    beklenenEkran: '"Ölçülmedi" yazılır',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['ENGINE'],
  },
  {
    id: 'ENV-GRN-001', alan: 'Envanter', rota: '—', eksen: 'veri',
    amac: 'Envanterde olup sahada görülmeyen varlığı bulmak',
    rol: 'sistem (motor)', kapsam: 'kurum geneli',
    onkosul: 'Varlık hiç keşifte görülmemiş', veriHali: 'yok',
    eylem: 'Motor koşar',
    beklenenSonuc: '"Hiç görülmedi" ile "eşikten uzun süre görülmedi" AYRI kurallardır',
    beklenenEkran: '—',
    beklenenIz: 'VeriKalitesiBulgusu · olusturma', beklenenBildirim: 'yok',
    katmanlar: ['ENGINE'],
  },

  /* ── Kuyruk · kütükte hiç yazılmamış bir giriş ────────────────────── */

  {
    id: 'SIS-KYR-001', alan: 'Sistem', rota: '—', eksen: 'akis',
    amac: 'Kuyruk sağlayıcısını değiştirmek',
    rol: 'geliştirici / işletme', kapsam: 'kurum geneli',
    onkosul: 'Aynı adla sağlayıcı zaten kayıtlı', veriHali: 'yinelenen',
    eylem: 'Aynı adla ikinci sağlayıcı kaydeder',
    beklenenSonuc: 'Reddedilir — üzerine yazmak AÇIKÇA istenmelidir; sessiz değişim işleri görünmez biçimde başka kuyruğa yollardı',
    beklenenEkran: '—',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER'],
  },
];
