import type { Senaryo } from './tipler';

/* Platform alanının senaryoları: oturum, yetki, yönetim konsolu,
   entegrasyon sağlığı, API, bildirim, rapor, içe/dışa aktarım, eşleme
   tezgâhı, sistem sayfaları, saha/portföy ve yardım.

   Bu alanın değişmezi: bağlı olmayan bir kaynak "hatalı" değildir,
   hiç koşmamış bir motor "sağlıklı" değildir ve bilinmeyen bir ölçü
   sıfır değildir. */

export const PLATFORM_SENARYOLARI: Senaryo[] = [
  /* ── Oturum ve giriş ────────────────────────────────────────────── */
  {
    id: 'OTR-GRS-001', alan: 'Oturum', rota: '/giris', eksen: 'yetki',
    amac: 'Sisteme girmek',
    rol: 'kayıtlı kullanıcı', kapsam: 'kendi hesabı',
    onkosul: 'Hesap aktif', veriHali: 'normal',
    eylem: 'Geçerli kimlikle giriş yapar',
    beklenenSonuc: 'Oturum açılır',
    beklenenEkran: 'Ana ekrana yönlendirilir',
    beklenenIz: 'Oturum kaydı', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'RBAC'],
  },
  {
    id: 'OTR-GRS-002', alan: 'Oturum', rota: '/giris', eksen: 'yetki',
    amac: 'Yetkisiz erişimin engellenmesi',
    rol: 'kimliksiz ziyaretçi', kapsam: 'yok',
    onkosul: 'Oturum yok', veriHali: 'yok',
    eylem: 'Korumalı bir ekranı doğrudan açmayı dener',
    beklenenSonuc: 'Girişe yönlendirilir; veri sızmaz',
    beklenenEkran: 'Giriş ekranı',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'RBAC'],
  },
  {
    id: 'OTR-GRS-003', alan: 'Oturum', rota: '/giris', eksen: 'yetki',
    amac: 'Demo oturumunun veri bozmaması',
    rol: 'demo kullanıcısı', kapsam: 'kurum geneli',
    onkosul: 'Demo oturumu açık', veriHali: 'normal',
    eylem: 'Bir yazma eylemi çağırır',
    beklenenSonuc: 'Reddedilir — demo salt okunurdur',
    beklenenEkran: 'Yazma düğmeleri kapalı',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'RBAC'],
  },
  {
    id: 'OTR-OTR-001', alan: 'Oturum', rota: '—', eksen: 'yetki',
    amac: 'Süresi geçen oturumun kapanması',
    rol: 'kayıtlı kullanıcı', kapsam: 'kendi hesabı',
    onkosul: 'Oturum süresi dolmuş', veriHali: 'bayat',
    eylem: 'Bir istek yapar',
    beklenenSonuc: 'Oturum reddedilir',
    beklenenEkran: 'Girişe döner',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'RBAC'],
  },

  /* ── Yetkiler ekranı ────────────────────────────────────────────── */
  {
    id: 'YTK-LST-001', alan: 'Yetkiler', rota: '/yetkiler', eksen: 'yetki',
    amac: 'Kimin neye yetkili olduğunu görmek',
    rol: 'kurum yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Kullanıcılar tanımlı', veriHali: 'normal',
    eylem: 'Yetkiler ekranını açar',
    beklenenSonuc: 'Rol ve santral kapsamıyla listelenir',
    beklenenEkran: 'Sahiplik yükü ve bekleyen zimmet görünür',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'UI'],
  },
  {
    id: 'YTK-LST-002', alan: 'Yetkiler', rota: '/yetkiler', eksen: 'yetki',
    amac: 'Yetki yönetiminin herkese açık olmaması',
    rol: 'BT yöneticisi', kapsam: 'tek santral',
    onkosul: 'Kullanıcı kurum yöneticisi değil', veriHali: 'normal',
    eylem: 'Yetki değiştirmeyi dener',
    beklenenSonuc: 'Reddedilir',
    beklenenEkran: 'Yazma yüzeyi açılmaz',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'RBAC'],
  },

  /* ── Yönetim konsolu ────────────────────────────────────────────── */
  {
    id: 'YON-AYR-001', alan: 'Yönetim konsolu', rota: '/ayarlar',
    eksen: 'yetki',
    amac: 'Bir eşiği kurumun gerçeğine göre ayarlamak',
    rol: 'kurum yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Kullanıcı yetkili', veriHali: 'normal',
    eylem: 'Bir ayarı değiştirir',
    beklenenSonuc: 'Değer doğrulanır ve kaydedilir',
    beklenenEkran: 'Değerin nereden geldiği (varsayılan/konsol) yazılı',
    beklenenIz: 'Yapilandirma · guncelleme',
    beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'RBAC', 'DOMAIN'],
  },
  {
    id: 'YON-AYR-002', alan: 'Yönetim konsolu', rota: '/ayarlar',
    eksen: 'veri',
    amac: 'Geçersiz değerin sisteme girmemesi',
    rol: 'kurum yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Şema bir aralık dayatıyor', veriHali: 'çelişen',
    eylem: 'Aralık dışı bir değer girer',
    beklenenSonuc: 'Reddedilir; eski değer korunur',
    beklenenEkran: 'Neyin beklendiği yazılır',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'DOMAIN'],
  },
  {
    id: 'YON-AYR-003', alan: 'Yönetim konsolu', rota: '/ayarlar',
    eksen: 'veri',
    amac: 'Bozuk kayıt yüzünden motorun durmaması',
    rol: 'sistem', kapsam: 'kurum geneli',
    onkosul: 'Saklanan değer şemayı geçmiyor', veriHali: 'çelişen',
    eylem: 'Ayar okunur',
    beklenenSonuc: 'Kod varsayılanı döner ve kaynak "geçersiz kayıt" olur',
    beklenenEkran: 'Konsolda bozukluk görünür',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN'],
  },
  {
    id: 'YON-MOD-001', alan: 'Yönetim konsolu', rota: '/yonetim-tezgahi',
    eksen: 'veri',
    amac: 'Hangi kuralın panelden yönetildiğini görmek',
    rol: 'kurum yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Modül kütüğü dolu', veriHali: 'normal',
    eylem: 'Yönetim tezgâhını açar',
    beklenenSonuc: 'A/B modüller yönetilebilir, C modüller gerekçesiyle kodda',
    beklenenEkran: 'Kapsama oranı C modülleri paydaya KATMAZ',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'UI'],
  },
  {
    id: 'YON-MOD-002', alan: 'Yönetim konsolu', rota: '—', eksen: 'veri',
    amac: 'Her ayarın bir yönetim yüzeyine bağlı olması',
    rol: 'geliştirici / denetçi', kapsam: 'kurum geneli',
    onkosul: '—', veriHali: 'normal',
    eylem: 'Ayar kütüğü ile modül kütüğü karşılaştırılır',
    beklenenSonuc: 'Modülsüz ayar YOKTUR',
    beklenenEkran: '—',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN'],
  },

  /* ── Entegrasyon sağlığı ────────────────────────────────────────── */
  {
    id: 'SAG-CON-001', alan: 'Sağlık', rota: '/saglik', eksen: 'entegrasyon',
    amac: 'Bağlantıların gerçekten çalışıp çalışmadığını görmek',
    rol: 'platform yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Connector hiç koşmamış', veriHali: 'yok',
    eylem: 'Sağlık ekranını açar',
    beklenenSonuc: '"Hiç koşmadı" yazılır; sağlıklı SAYILMAZ',
    beklenenEkran: 'Bilinmeyen işaretçisi; yeşil DEĞİL',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'UI'],
  },
  {
    id: 'SAG-CON-002', alan: 'Sağlık', rota: '/saglik', eksen: 'entegrasyon',
    amac: 'Kimlik bekleyen kurulumun hata sanılmaması',
    rol: 'platform yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Connector durumu kimlik_bekleniyor', veriHali: 'kısmi',
    eylem: 'Sağlık ekranını açar',
    beklenenSonuc: 'Bekleyen kurulum adımı olarak gösterilir',
    beklenenEkran: 'Kırmızı DEĞİL',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'UI'],
  },
  {
    id: 'SAG-CON-003', alan: 'Sağlık', rota: '/saglik', eksen: 'entegrasyon',
    amac: 'Ardışık hatanın sessizce sürmemesi',
    rol: 'platform yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Ardışık hata sınırı aşılmış', veriHali: 'kısmi',
    eylem: 'Senkronizasyon koşar',
    beklenenSonuc: 'Devre kesici connector\'ı duraklatır',
    beklenenEkran: 'Durum "hatalı" olur ve görünür',
    beklenenIz: 'Koşu kaydı', beklenenBildirim: 'yok',
    katmanlar: ['INTEGRATION', 'ENGINE'],
  },
  {
    id: 'SAG-CON-004', alan: 'Sağlık', rota: '/saglik', eksen: 'entegrasyon',
    amac: 'Geçici hatada verinin kaybolmaması',
    rol: 'platform yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Kaynak zaman aşımı veriyor', veriHali: 'kısmi',
    eylem: 'Senkronizasyon koşar',
    beklenenSonuc: 'Geri çekilmeyle tekrar denenir',
    beklenenEkran: 'Deneme sayısı görünür',
    beklenenIz: 'Koşu kaydı', beklenenBildirim: 'yok',
    katmanlar: ['INTEGRATION'],
  },
  {
    id: 'SAG-CON-005', alan: 'Sağlık', rota: '/saglik', eksen: 'entegrasyon',
    amac: 'Kalıcı yetki hatasında boşuna denenmemesi',
    rol: 'platform yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Kaynak 401 döndürüyor', veriHali: 'kısmi',
    eylem: 'Senkronizasyon koşar',
    beklenenSonuc: 'Tekrar DENENMEZ',
    beklenenEkran: 'Hata sebebi yazılır',
    beklenenIz: 'Koşu kaydı', beklenenBildirim: 'yok',
    katmanlar: ['INTEGRATION'],
  },
  {
    id: 'SAG-CON-006', alan: 'Sağlık', rota: '/saglik', eksen: 'entegrasyon',
    amac: 'Aynı kaydın iki koşuda iki kez yazılmaması',
    rol: 'platform yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Aynı kaynak kaydı tekrar geliyor', veriHali: 'yinelenen',
    eylem: 'İkinci koşuyu çalıştırır',
    beklenenSonuc: 'Kayıt tazelenir, kopyalanmaz',
    beklenenEkran: 'Yinelenen sayacı artar',
    beklenenIz: 'Köken kaydı', beklenenBildirim: 'yok',
    katmanlar: ['INTEGRATION', 'CONCURRENCY'],
  },
  {
    id: 'SAG-CON-007', alan: 'Sağlık', rota: '/saglik', eksen: 'yetki',
    amac: 'Sırların ekrana hiç çıkmaması',
    rol: 'platform yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Connector bir sır referansı taşıyor', veriHali: 'normal',
    eylem: 'Connector çekmecesini açar',
    beklenenSonuc: 'Yalnız maske görünür; sır DEĞERİ hiç taşınmaz',
    beklenenEkran: 'Maskelenmiş referans',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'RBAC'],
  },
  {
    id: 'SAG-KUR-001', alan: 'Sağlık', rota: '/saglik', eksen: 'entegrasyon',
    amac: 'Bağlanmadan önce ne olacağını görmek',
    rol: 'platform yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Connector yapılandırılmış', veriHali: 'normal',
    eylem: 'Kuru koşu çalıştırır',
    beklenenSonuc: 'Hiçbir kayıt YAZILMAZ; sayaçlar gösterilir',
    beklenenEkran: 'Kuru koşu desteklenmiyorsa açıkça söylenir',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['INTEGRATION'],
  },
  {
    id: 'SAG-RED-001', alan: 'Sağlık', rota: '/saglik/reddedilenler',
    eksen: 'veri',
    amac: 'Kabul edilmeyen kayıtların nedenini görmek',
    rol: 'platform yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Reddedilen kayıt var', veriHali: 'kısmi',
    eylem: 'Reddedilenler ekranını açar',
    beklenenSonuc: 'Aşama ve sebep listelenir',
    beklenenEkran: 'Kayıt sessizce düşmez',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'UI'],
  },
  {
    id: 'SAG-MOT-001', alan: 'Sağlık', rota: '/saglik', eksen: 'veri',
    amac: 'Motorların koşup koşmadığını görmek',
    rol: 'platform yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Motor kütüğü dolu', veriHali: 'normal',
    eylem: 'Sağlık ekranını açar',
    beklenenSonuc: 'Her motorun son koşusu ve sonucu görünür',
    beklenenEkran: 'Hiç koşmamış motor ayrı gösterilir',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'ENGINE'],
  },
  {
    id: 'SAG-MOT-002', alan: 'Sağlık', rota: '—', eksen: 'veri',
    amac: 'Motor kütüğünün ekranla ayrışmaması',
    rol: 'geliştirici / denetçi', kapsam: 'kurum geneli',
    onkosul: '—', veriHali: 'normal',
    eylem: 'Kütük, sözlük ve iş tanımları karşılaştırılır',
    beklenenSonuc: 'Üçü de AYNI motor kümesini söyler',
    beklenenEkran: '—',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'ENGINE'],
  },

  /* ── API ────────────────────────────────────────────────────────── */
  {
    id: 'API-KIM-001', alan: 'API', rota: '—', eksen: 'yetki',
    amac: 'Anahtarsız isteğin veri göstermemesi',
    rol: 'API istemcisi', kapsam: 'yok',
    onkosul: 'Anahtar gönderilmiyor', veriHali: 'yok',
    eylem: 'Bir ucu çağırır',
    beklenenSonuc: '401 döner ve gövdede kayıt bulunmaz',
    beklenenEkran: '—',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['API', 'RBAC'],
  },
  {
    id: 'API-KIM-002', alan: 'API', rota: '—', eksen: 'yetki',
    amac: 'Süresi dolmuş ya da iptal edilmiş anahtarın çalışmaması',
    rol: 'API istemcisi', kapsam: 'yok',
    onkosul: 'Anahtar iptal ya da süresi dolmuş', veriHali: 'bayat',
    eylem: 'Bir ucu çağırır',
    beklenenSonuc: '401 döner',
    beklenenEkran: '—',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['API', 'RBAC'],
  },
  {
    id: 'API-KIM-003', alan: 'API', rota: '—', eksen: 'yetki',
    amac: 'Anahtarın veritabanında açık durmaması',
    rol: 'güvenlik denetçisi', kapsam: 'kurum geneli',
    onkosul: 'Anahtarlar üretilmiş', veriHali: 'normal',
    eylem: 'Anahtar tablosunu inceler',
    beklenenSonuc: 'Yalnız SHA-256 özeti ve kısa ön ek saklanır',
    beklenenEkran: '—',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['API', 'RBAC'],
  },
  {
    id: 'API-KPS-001', alan: 'API', rota: '—', eksen: 'yetki',
    amac: 'Salt okunur anahtarın yazamaması',
    rol: 'API istemcisi', kapsam: 'salt okunur',
    onkosul: 'Anahtar salt okunur işaretli', veriHali: 'normal',
    eylem: 'Bir yazma ucunu çağırır',
    beklenenSonuc: 'Reddedilir',
    beklenenEkran: '—',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['API', 'RBAC'],
  },
  {
    id: 'API-KPS-002', alan: 'API', rota: '—', eksen: 'yetki',
    amac: 'Anahtarın santral kapsamının dışına çıkmaması',
    rol: 'API istemcisi', kapsam: 'tek santral',
    onkosul: 'Kurumda başka santraller de var', veriHali: 'normal',
    eylem: 'Varlık listesini okur',
    beklenenSonuc: 'Yalnız kendi santralinin kayıtları döner',
    beklenenEkran: '—',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['API', 'SCOPE'],
  },
  {
    id: 'API-KPS-003', alan: 'API', rota: '—', eksen: 'veri',
    amac: 'Uç kütüğünün sözleşmeyle ayrışmaması',
    rol: 'geliştirici / denetçi', kapsam: 'kurum geneli',
    onkosul: '—', veriHali: 'normal',
    eylem: 'Uç dosyaları, kapsam listesi ve OpenAPI karşılaştırılır',
    beklenenSonuc: 'Üçü de AYNI uç kümesini söyler',
    beklenenEkran: '—',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['API', 'DOMAIN'],
  },
  {
    id: 'API-DGR-001', alan: 'API', rota: '—', eksen: 'veri',
    amac: 'Bozuk yükün hangi alanda bozuk olduğunu öğrenmek',
    rol: 'API istemcisi', kapsam: 'anahtarın kapsamı',
    onkosul: 'Zorunlu bir alan eksik', veriHali: 'kısmi',
    eylem: 'Eksik gövdeyle gönderir',
    beklenenSonuc: '400 döner ve eksik alan adlandırılır',
    beklenenEkran: '—',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['API'],
  },
  {
    id: 'API-IDM-001', alan: 'API', rota: '—', eksen: 'veri',
    amac: 'Tekrar gönderilen isteğin kaydı ikilememesi',
    rol: 'API istemcisi', kapsam: 'anahtarın kapsamı',
    onkosul: 'Aynı kaynak kaydı iki kez gönderiliyor',
    veriHali: 'yinelenen',
    eylem: 'İkinci isteği gönderir',
    beklenenSonuc: 'Kayıt tazelenir, yeni satır açılmaz',
    beklenenEkran: '—',
    beklenenIz: 'Köken kaydı', beklenenBildirim: 'yok',
    katmanlar: ['API', 'CONCURRENCY'],
  },

  /* ── Bildirim ve görev ──────────────────────────────────────────── */
  {
    id: 'BLD-KTU-001', alan: 'Bildirim', rota: '/bildirimler', eksen: 'veri',
    amac: 'Bana düşen işleri görmek',
    rol: 'herhangi bir kullanıcı', kapsam: 'kendi kutusu',
    onkosul: 'Okunmamış bildirim var', veriHali: 'normal',
    eylem: 'Bildirimler ekranını açar',
    beklenenSonuc: 'Yalnız kendi kutusundakiler görünür',
    beklenenEkran: 'Sayaç sıfırda rozet çizmez',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'SCOPE'],
  },
  {
    id: 'BLD-KTU-002', alan: 'Bildirim', rota: '/bildirimler', eksen: 'akis',
    amac: 'Bildirimi okundu işaretlemek',
    rol: 'herhangi bir kullanıcı', kapsam: 'kendi kutusu',
    onkosul: 'Okunmamış bildirim var', veriHali: 'normal',
    eylem: 'Okundu işaretler',
    beklenenSonuc: 'Yalnız kendi kutusunda okundu olur; kayıt kapanmaz',
    beklenenEkran: 'Sayaç düşer',
    beklenenIz: 'Bildirim · guncelleme', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'SCOPE'],
  },

  /* ── Rapor ──────────────────────────────────────────────────────── */
  {
    id: 'RAP-URT-001', alan: 'Rapor', rota: '/raporlar', eksen: 'veri',
    amac: 'Yönetime sunulacak özeti almak',
    rol: 'uyum yöneticisi', kapsam: 'kendi santrali',
    onkosul: 'Veri var', veriHali: 'normal',
    eylem: 'Raporu dışa aktarır',
    beklenenSonuc: 'Sayfa başına Excel ve CSV üretilir',
    beklenenEkran: 'Hangi sayfanın indirileceği açık',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'UI'],
  },
  {
    id: 'RAP-URT-002', alan: 'Rapor', rota: '/raporlar', eksen: 'yetki',
    amac: 'Raporun kapsam dışına çıkmaması',
    rol: 'uyum uzmanı', kapsam: 'tek santral',
    onkosul: 'Kurumda başka santraller var', veriHali: 'normal',
    eylem: 'Rapor üretir',
    beklenenSonuc: 'Yalnız kendi kapsamı raporlanır',
    beklenenEkran: 'Sayılar ekranla aynı',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'SCOPE'],
  },

  /* ── İçe aktarım ve eşleme ──────────────────────────────────────── */
  {
    id: 'IMP-XLS-001', alan: 'İçe aktarım', rota: '/ice-aktarim',
    eksen: 'veri',
    amac: 'Elde olan listeyi sisteme almak',
    rol: 'BT yöneticisi', kapsam: 'kendi santrali',
    onkosul: 'Dosya geçerli', veriHali: 'normal',
    eylem: 'Dosyayı yükler',
    beklenenSonuc: 'Kayıtlar ayrıştırılır ve önizlenir',
    beklenenEkran: 'Yazmadan önce ne olacağı gösterilir',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'DOMAIN'],
  },
  {
    id: 'IMP-XLS-002', alan: 'İçe aktarım', rota: '/ice-aktarim',
    eksen: 'veri',
    amac: 'Bozuk dosyanın veriyi kirletmemesi',
    rol: 'BT yöneticisi', kapsam: 'kendi santrali',
    onkosul: 'Dosyada eksik/bozuk satır var', veriHali: 'kısmi',
    eylem: 'Dosyayı yükler',
    beklenenSonuc: 'Bozuk satır reddedilir ve sebebi yazılır',
    beklenenEkran: 'Kaç satır kabul, kaç satır ret — ayrı',
    beklenenIz: 'Reddedilen kayıt', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'DOMAIN'],
  },
  {
    id: 'ESL-PRF-001', alan: 'Eşleme', rota: '/esleme', eksen: 'veri',
    amac: 'Kaynak alanını hedef alana bağlamak',
    rol: 'platform yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Profil taslak', veriHali: 'normal',
    eylem: 'Eşleme kuralı ekler ve profili etkinleştirir',
    beklenenSonuc: 'Yeni sürüm açılır; eski sürüm EZİLMEZ',
    beklenenEkran: 'Sürüm numarası görünür',
    beklenenIz: 'Profil · olusturma', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'DOMAIN'],
  },
  {
    id: 'ESL-PRF-002', alan: 'Eşleme', rota: '/esleme', eksen: 'veri',
    amac: 'Eşlemenin örnek veriyle sınanabilmesi',
    rol: 'platform yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Örnek kayıt girilmiş', veriHali: 'normal',
    eylem: 'Önizleme çalıştırır',
    beklenenSonuc: 'Sonuç gösterilir; hiçbir kayıt yazılmaz',
    beklenenEkran: 'Dönüşen alanlar yan yana',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'DOMAIN'],
  },

  /* ── Sistem sayfaları ve kabuk ──────────────────────────────────── */
  {
    id: 'SIS-HTA-001', alan: 'Sistem', rota: '—', eksen: 'arayuz',
    amac: 'Olmayan bir adreste kaybolmamak',
    rol: 'herhangi bir kullanıcı', kapsam: 'kendi kapsamı',
    onkosul: 'Adres yok', veriHali: 'yok',
    eylem: 'Geçersiz bir adres açar',
    beklenenSonuc: 'Bulunamadı sayfası ve dönüş yolu gösterilir',
    beklenenEkran: 'Ana ekrana bağ',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['UI'],
  },
  {
    id: 'SIS-KBK-001', alan: 'Sistem', rota: '—', eksen: 'arayuz',
    amac: 'Her ekranda nerede olduğunu bilmek',
    rol: 'herhangi bir kullanıcı', kapsam: 'kendi kapsamı',
    onkosul: 'Kullanıcı giriş yapmış', veriHali: 'normal',
    eylem: 'Rotalar arasında gezinir',
    beklenenSonuc: 'Aktif bölüm gezinmede işaretlidir',
    beklenenEkran: 'Her sayfada tek bir ana bölge bulunur',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['UI', 'ACCESSIBILITY'],
  },
  {
    id: 'SIS-ERS-001', alan: 'Sistem', rota: '—', eksen: 'arayuz',
    amac: 'Klavyeyle çalışabilmek',
    rol: 'klavye kullanıcısı', kapsam: 'kendi kapsamı',
    onkosul: 'Fare kullanılmıyor', veriHali: 'normal',
    eylem: 'Sekme ile gezinir',
    beklenenSonuc: 'Odak görünür ve sıra mantıklıdır',
    beklenenEkran: 'Çekmecede odak tuzağı ve ESC çalışır',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['ACCESSIBILITY', 'UI'],
  },
  {
    id: 'SIS-RSP-001', alan: 'Sistem', rota: '—', eksen: 'arayuz',
    amac: 'Dar ekranda bilgi kaybetmemek',
    rol: 'sahadaki kullanıcı', kapsam: 'kendi kapsamı',
    onkosul: 'Ekran dar', veriHali: 'normal',
    eylem: 'Ekranı daraltır',
    beklenenSonuc: 'Sayfa yatay kaymaz; içerik yeniden akar',
    beklenenEkran: 'Kritik bilgi gizlenmez',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['RESPONSIVE', 'UI'],
  },
  {
    id: 'SIS-DIL-001', alan: 'Sistem', rota: '—', eksen: 'arayuz',
    amac: 'Ekranda geliştirici diliyle karşılaşmamak',
    rol: 'son kullanıcı', kapsam: 'kendi kapsamı',
    onkosul: '—', veriHali: 'normal',
    eylem: 'Ekranlardaki metinleri okur',
    beklenenSonuc: 'Kullanıcıya dönük metinlerde teknik jargon yoktur',
    beklenenEkran: 'Türkçe, kısa, kurumsal',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['UI'],
  },

  /* ── Saha ve portföy ────────────────────────────────────────────── */
  {
    id: 'PRT-OZT-001', alan: 'Portföy', rota: '/portfoy', eksen: 'veri',
    amac: 'Bütün santrallerin durumunu tek bakışta görmek',
    rol: 'kurum yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Santraller tanımlı', veriHali: 'normal',
    eylem: 'Portföy ekranını açar',
    beklenenSonuc: 'Santral başına özet görünür',
    beklenenEkran: 'Ölçülmemiş değer sıfıra çekilmez',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'UI'],
  },
  {
    id: 'PRT-OZT-002', alan: 'Portföy', rota: '/tesisler/[id]', eksen: 'veri',
    amac: 'Tek bir santralin bütün resmini görmek',
    rol: 'santral sorumlusu', kapsam: 'kendi santrali',
    onkosul: 'Santral kimliği geçerli', veriHali: 'normal',
    eylem: 'Santral detayını açar',
    beklenenSonuc: 'Varlık, uyum, risk ve olay özetleri birlikte görünür',
    beklenenEkran: 'Fotoğrafı olmayan santral tipografik karşılık alır',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'UI'],
  },
  {
    id: 'HRT-KNM-001', alan: 'Harita', rota: '/harita', eksen: 'veri',
    amac: 'Santrallerin coğrafi dağılımını görmek',
    rol: 'kurum yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Koordinatı olmayan santral var', veriHali: 'kısmi',
    eylem: 'Haritayı açar',
    beklenenSonuc: 'Koordinatsız santral uydurma bir yere KONMAZ',
    beklenenEkran: 'Listede ayrıca sayılır',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'UI'],
  },

  /* ── Yardım ─────────────────────────────────────────────────────── */
  {
    id: 'YRD-SOR-001', alan: 'Yardım', rota: '/yardim', eksen: 'arayuz',
    amac: 'Bir ekranı nasıl okuyacağını öğrenmek',
    rol: 'yeni kullanıcı', kapsam: 'kendi kapsamı',
    onkosul: '—', veriHali: 'normal',
    eylem: 'Yardım ekranını açar',
    beklenenSonuc: 'Durum sözcükleri ve iş kuralları kaynağıyla açıklanır',
    beklenenEkran: 'Her cevabın altında kural dosyası anılır',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'UI'],
  },
];

/* ── İkinci dalga: kalan platform yüzeyleri ─────────────────────────── */

export const PLATFORM_SENARYOLARI_2: Senaryo[] = [
  {
    id: 'OTR-HSP-001', alan: 'Oturum', rota: '/ayarlar', eksen: 'yetki',
    amac: 'Kendi parolamı güvenli biçimde değiştirmek',
    rol: 'kayıtlı kullanıcı', kapsam: 'kendi hesabı',
    onkosul: 'Yeni parola kısa', veriHali: 'çelişen',
    eylem: 'Parolayı değiştirmeyi dener',
    beklenenSonuc: 'Reddedilir; alt sınır söylenir',
    beklenenEkran: 'Boş alan sessizdir, kusur cümlesi üretmez',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'DOMAIN'],
  },
  {
    id: 'OTR-HSP-002', alan: 'Oturum', rota: '/ayarlar', eksen: 'yetki',
    amac: 'Başka cihazlardaki oturumlarımı kapatmak',
    rol: 'kayıtlı kullanıcı', kapsam: 'kendi hesabı',
    onkosul: 'Birden çok oturum açık', veriHali: 'normal',
    eylem: 'Tüm oturumları kapatır',
    beklenenSonuc: 'Yalnız KENDİ oturumları kapanır',
    beklenenEkran: 'Kaç oturumun kapandığı söylenir',
    beklenenIz: 'Oturum · guncelleme', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'RBAC'],
  },
  {
    id: 'YTK-ATM-001', alan: 'Yetkiler', rota: '/yetkiler', eksen: 'yetki',
    amac: 'Aynı yetkinin iki kez yazılmaması',
    rol: 'kurum yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Aynı atama zaten var', veriHali: 'yinelenen',
    eylem: 'Aynı atamayı tekrar yapar',
    beklenenSonuc: 'İkinci satır AÇILMAZ',
    beklenenEkran: 'Farklı seviye de ikinci satır açmaz — aynı erişimin değişimidir',
    beklenenIz: 'Yetki · guncelleme', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'DOMAIN'],
  },
  {
    id: 'KIM-HSP-001', alan: 'Kimlik', rota: '/kimlik', eksen: 'yetki',
    amac: 'Bir sistem hesabını kayda geçirmek',
    rol: 'BT yöneticisi', kapsam: 'tek santral',
    onkosul: 'Hesap başka santralde açılmak isteniyor', veriHali: 'normal',
    eylem: 'Hesap açmayı dener',
    beklenenSonuc: 'Reddedilir; santralsiz hesap kapsamsız yetki ister',
    beklenenEkran: 'Ayrıcalık ÜÇ DURUMLUDUR — null "yok" değildir',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'SCOPE'],
  },
  {
    id: 'KIM-ERS-001', alan: 'Kimlik', rota: '/kimlik', eksen: 'veri',
    amac: 'Riskli erişimleri görmek',
    rol: 'güvenlik uzmanı', kapsam: 'kendi santrali',
    onkosul: 'Bazı alanlar ölçülmemiş', veriHali: 'bilinmiyor',
    eylem: 'Erişim değerlendirmesine bakar',
    beklenenSonuc: 'null ile false KARIŞTIRILMAZ — biri ihlal, öteki boşluk',
    beklenenEkran: 'Kritik olmamak "kritikliği düşük" demek değildir',
    beklenenIz: 'yazma yok', beklenenBildirim: 'Görev',
    katmanlar: ['ENGINE', 'DOMAIN'],
  },
  {
    id: 'TED-OTR-001', alan: 'Tedarikçi', rota: '/tedarikciler',
    eksen: 'entegrasyon',
    amac: 'Tedarikçi uzaktan bağlantılarını görmek',
    rol: 'güvenlik uzmanı', kapsam: 'kendi santrali',
    onkosul: 'Hiç kayıt yok', veriHali: 'yok',
    eylem: 'Tedarikçi oturumlarına bakar',
    beklenenSonuc: 'Durum "kaynak bağlı değil" — "oturum yok" DEĞİL',
    beklenenEkran: 'Uyumsuz ile bilinmeyen ayrı sayılır',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'INTEGRATION'],
  },
  {
    id: 'OPR-DEG-001', alan: 'Operasyon', rota: '/operasyon', eksen: 'akis',
    amac: 'Bir değişikliği kayda geçirmek',
    rol: 'operasyon sorumlusu', kapsam: 'tek santral',
    onkosul: 'Değişiklik başka santrale ait', veriHali: 'normal',
    eylem: 'Değişiklik kaydetmeyi dener',
    beklenenSonuc: 'Reddedilir',
    beklenenEkran: 'Kaydın GERÇEK santrali güncellemede de bağlayıcıdır',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'SCOPE'],
  },
  {
    id: 'OPR-DEG-002', alan: 'Operasyon', rota: '/operasyon', eksen: 'veri',
    amac: 'OT değişikliğinin ek kapılardan geçmesi',
    rol: 'operasyon sorumlusu', kapsam: 'kendi santrali',
    onkosul: 'Değişiklik BT tarafında', veriHali: 'normal',
    eylem: 'Kapı sayacına bakar',
    beklenenSonuc: 'BT değişikliğinin kapısı YOKTUR — "0/5" uydurulmaz',
    beklenenEkran: 'OT değişikliği beş kapı taşır',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN'],
  },
  {
    id: 'TES-PRF-001', alan: 'Portföy', rota: '/tesisler/[id]', eksen: 'veri',
    amac: 'Santral profilini doldurmak',
    rol: 'santral sorumlusu', kapsam: 'kendi santrali',
    onkosul: 'Bazı alanlar boş bırakıldı', veriHali: 'kısmi',
    eylem: 'Profili kaydeder',
    beklenenSonuc: 'Boş metin NULL olur — "" ile "bilinmiyor" ayrıdır',
    beklenenEkran: 'Üç durumlu alanlarda false ile null ayrı saklanır',
    beklenenIz: 'Profil · guncelleme', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'DOMAIN'],
  },
  {
    id: 'TES-PRF-002', alan: 'Portföy', rota: '/tesisler/[id]', eksen: 'akis',
    amac: 'Motorun insanın kararını ezmemesi',
    rol: 'santral sorumlusu', kapsam: 'kendi santrali',
    onkosul: 'İnsan kararı gerekçesiyle yazılmış', veriHali: 'çelişen',
    eylem: 'Uygulanabilirlik motoru yeniden koşar',
    beklenenSonuc: 'İnsanın kararı KORUNUR',
    beklenenEkran: 'Elle değiştirildi işareti görünür',
    beklenenIz: 'Karar satırı', beklenenBildirim: 'yok',
    katmanlar: ['ENGINE', 'SERVER'],
  },
  {
    id: 'TES-PRF-003', alan: 'Portföy', rota: '/tesisler/[id]', eksen: 'veri',
    amac: 'Profilsiz santralin uyum hesabını bozmaması',
    rol: 'uyum uzmanı', kapsam: 'kurum geneli',
    onkosul: 'Yeni santral açıldı, profili yok', veriHali: 'yok',
    eylem: 'Uygulanabilirlik motoru koşar',
    beklenenSonuc: 'Karar VERİLMEZ ve veri kalitesi bulgusu açılır',
    beklenenEkran: 'Profil gelince kapsam kendiliğinden hesaplanır',
    beklenenIz: 'Bulgu', beklenenBildirim: 'Veri kalitesi bulgusu',
    katmanlar: ['ENGINE', 'DOMAIN'],
  },
  {
    id: 'KNM-KRD-001', alan: 'Harita', rota: '/tesisler/[id]', eksen: 'veri',
    amac: 'Santralin konumunu düzeltmek',
    rol: 'santral sorumlusu', kapsam: 'kendi santrali',
    onkosul: 'Yalnız enlem girildi', veriHali: 'kısmi',
    eylem: 'Koordinatı kaydetmeyi dener',
    beklenenSonuc: 'YARIM koordinat reddedilir',
    beklenenEkran: 'Silme meşrudur; iki alan birlikte boşaltılabilir',
    beklenenIz: 'Tesis · guncelleme', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'DOMAIN'],
  },
  {
    id: 'SAG-KOK-001', alan: 'Sağlık', rota: '/saglik', eksen: 'veri',
    amac: 'Bir kaydın nereden geldiğini bilmek',
    rol: 'platform yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Kaydın köken satırı yok', veriHali: 'bilinmiyor',
    eylem: 'Köken bölümüne bakar',
    beklenenSonuc: 'Kayıt MANUEL sayılır; "otomatik" kovasına GİRMEZ',
    beklenenEkran: 'null "ölçülmedi" yazar, 0 "%0" yazar — ikisi ayrı',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'UI'],
  },
  {
    id: 'SAG-KOK-002', alan: 'Sağlık', rota: '/saglik', eksen: 'yetki',
    amac: 'Köken doğrulamasının kapsamla sınırlı kalması',
    rol: 'BT yöneticisi', kapsam: 'tek santral',
    onkosul: 'Parti içinde kapsam dışı bir kayıt var', veriHali: 'kısmi',
    eylem: 'Toplu doğrulama yapar',
    beklenenSonuc: 'Kapsam dışı TEK kayıt bütün partiyi durdurur',
    beklenenEkran: 'Yarım onay bırakılmaz',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'SCOPE'],
  },
  {
    id: 'SAG-SRT-001', alan: 'Sağlık', rota: '/saglik', eksen: 'entegrasyon',
    amac: 'Bir adaptörün sözleşmeye uyduğunu görmek',
    rol: 'platform yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Adaptör bağlı değil', veriHali: 'yok',
    eylem: 'Sertifikasyon raporuna bakar',
    beklenenSonuc: 'Bağlantı isteyen kontroller "uygulanamaz"dır, "kaldı" DEĞİL',
    beklenenEkran: 'Eksik sır bir kusur değil, kurulum adımıdır',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['INTEGRATION'],
  },
  {
    id: 'SAG-YAP-001', alan: 'Sağlık', rota: '/saglik', eksen: 'entegrasyon',
    amac: 'Bir bağlantıyı yapılandırmak',
    rol: 'platform yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Sır referansı biçimi bozuk', veriHali: 'çelişen',
    eylem: 'Yapılandırmayı kaydetmeyi dener',
    beklenenSonuc: 'Reddedilir; sır DEĞERİ hiç istenmez',
    beklenenEkran: 'Form kayıtlı referansı geri doldurmaz',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'INTEGRATION'],
  },
  {
    id: 'SAG-ESL-001', alan: 'Sağlık', rota: '/esleme', eksen: 'veri',
    amac: 'Gelen alanın güvenini bilmek',
    rol: 'platform yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Hiçbir güven kuralı tanımlı değil', veriHali: 'bilinmiyor',
    eylem: 'Önizleme çalıştırır',
    beklenenSonuc: 'Güven ÖLÇÜLMEDİ (null) — sıfır DEĞİL',
    beklenenEkran: 'Varsayılan bir ÖLÇÜM DEĞİLDİR',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'INTEGRATION'],
  },
  {
    id: 'SAG-ADV-001', alan: 'Sağlık', rota: '/saglik', eksen: 'entegrasyon',
    amac: 'Zafiyet duyurularını almak',
    rol: 'güvenlik uzmanı', kapsam: 'kurum geneli',
    onkosul: 'Gelen belge bozuk', veriHali: 'çelişen',
    eylem: 'Duyuru belgesini yükler',
    beklenenSonuc: 'İstisna FIRLATILMAZ; reddedilen olarak gerekçesiyle döner',
    beklenenEkran: 'Boş dizi bir hata değildir',
    beklenenIz: 'Reddedilen kayıt', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'INTEGRATION'],
  },
  {
    id: 'YON-MOT-001', alan: 'Yönetim konsolu', rota: '/saglik', eksen: 'yetki',
    amac: 'Motorları elle çalıştırmak',
    rol: 'platform yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Kullanıcının yönetim yazma yetkisi yok', veriHali: 'normal',
    eylem: 'Motorları çalıştırmayı dener',
    beklenenSonuc: 'Tek motora bile DOKUNULMAZ',
    beklenenEkran: 'Düğme kapalı',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'RBAC'],
  },
  {
    id: 'YON-MOT-002', alan: 'Yönetim konsolu', rota: '—', eksen: 'akis',
    amac: 'Motor zincirinin gereksiz koşmaması',
    rol: 'sistem (zamanlayıcı)', kapsam: 'kurum geneli',
    onkosul: 'Yalnız kanıt değişmiş', veriHali: 'kısmi',
    eylem: 'Zincir koşar',
    beklenenSonuc: 'İlgisiz motor KOŞMAZ; bir motor patlarsa zincir devam eder',
    beklenenEkran: 'Sonuç neyin atlandığını bildirir',
    beklenenIz: 'Koşu kaydı', beklenenBildirim: 'yok',
    katmanlar: ['ENGINE'],
  },
  {
    id: 'YON-KLT-001', alan: 'Yönetim konsolu', rota: '—', eksen: 'akis',
    amac: 'Aynı işin iki kez koşmaması',
    rol: 'sistem (zamanlayıcı)', kapsam: 'kurum geneli',
    onkosul: 'İki istek aynı anda geliyor', veriHali: 'yinelenen',
    eylem: 'Kilit alınmaya çalışılır',
    beklenenSonuc: 'Yalnız BİRİ kazanır; kirası dolmuş kilit devralınır',
    beklenenEkran: 'Kimin tuttuğu söylenir',
    beklenenIz: 'Kilit kaydı', beklenenBildirim: 'yok',
    katmanlar: ['CONCURRENCY', 'ENGINE'],
  },
  {
    id: 'YON-OTO-001', alan: 'Yönetim konsolu', rota: '—', eksen: 'akis',
    amac: 'Otomasyonun insan kararı yerine geçmemesi',
    rol: 'güvenlik denetçisi', kapsam: 'kurum geneli',
    onkosul: '—', veriHali: 'normal',
    eylem: 'Otomasyon sınırları ölçülür',
    beklenenSonuc: 'Her yasak için bir ÖLÇÜ vardır — yorumda kalan kural yok',
    beklenenEkran: '—',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['ENGINE', 'DOMAIN'],
  },
  {
    id: 'SIS-KPS-001', alan: 'Sistem', rota: '—', eksen: 'yetki',
    amac: 'Ekranın açtığı yazma yüzeyinin sunucuyla aynı cevabı vermesi',
    rol: 'geliştirici / denetçi', kapsam: 'kurum geneli',
    onkosul: '—', veriHali: 'normal',
    eylem: 'Ekran kapısı ile sunucu kapısı karşılaştırılır',
    beklenenSonuc: 'İki kapı AYNI yanıtı verir',
    beklenenEkran: 'Ekran sunucudan dar da geniş de değildir',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['RBAC', 'SCOPE'],
  },
  {
    id: 'SIS-KPS-002', alan: 'Sistem', rota: '—', eksen: 'yetki',
    amac: 'İki aşamalı kapının doğru kullanılması',
    rol: 'geliştirici / denetçi', kapsam: 'kurum geneli',
    onkosul: '—', veriHali: 'normal',
    eylem: 'Kapsam sonrası bildiren her eylem taranır',
    beklenenSonuc: 'Ön kapı TEK BAŞINA yetki VERMEZ; ikinci aşama zorunludur',
    beklenenEkran: '—',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['RBAC', 'SCOPE'],
  },
  {
    id: 'SIS-GVN-001', alan: 'Sistem', rota: '—', eksen: 'yetki',
    amac: 'Kapsam dışı verinin hiçbir yoldan sızmaması',
    rol: 'güvenlik denetçisi', kapsam: 'tek santral',
    onkosul: 'Kapsam dışı kayıt veritabanında GERÇEKTEN var',
    veriHali: 'normal',
    eylem: 'Liste, filtre ve yazma yolları denenir',
    beklenenSonuc: 'Hiçbiri kaydı döndürmez, ima etmez ya da yazdırmaz',
    beklenenEkran: 'Açıkça istenen kapsam dışı sorgu 403 döner',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['API', 'SCOPE', 'RBAC'],
  },
  {
    id: 'SIS-SIR-001', alan: 'Sistem', rota: '—', eksen: 'yetki',
    amac: 'Sır değerinin veritabanına ve ekrana hiç girmemesi',
    rol: 'güvenlik denetçisi', kapsam: 'kurum geneli',
    onkosul: 'Sır referansı tanımlı', veriHali: 'normal',
    eylem: 'Sır katmanı çözümlenir',
    beklenenSonuc: 'Yalnız referans saklanır; tanınmayan sağlayıcı denetimden GEÇMEZ',
    beklenenEkran: 'Bağlı olup olmadığı ayrıca bildirilir',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'INTEGRATION'],
  },
  {
    id: 'SIS-ALT-001', alan: 'Sistem', rota: '/saglik', eksen: 'entegrasyon',
    amac: 'Üretime hazır olup olmadığımızı görmek',
    rol: 'platform yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Zorunlu bir kontrol ölçülemedi', veriHali: 'bilinmiyor',
    eylem: 'Hazırlık özetine bakar',
    beklenenSonuc: 'HAZIR cümlesi KURULMAZ',
    beklenenEkran: 'Ölçülemeyen zorunlu kontrol ayrı sayılır',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'INTEGRATION'],
  },
];

/* ── Üçüncü dalga: motor kütüğü ve veri kalitesi ────────────────────── */

export const PLATFORM_SENARYOLARI_3: Senaryo[] = [
  {
    id: 'YON-MOT-003', alan: 'Yönetim konsolu', rota: '/saglik', eksen: 'veri',
    amac: 'Kütükteki her motorun gerçekten çalıştırılabilir olması',
    rol: 'geliştirici / denetçi', kapsam: 'kurum geneli',
    onkosul: '—', veriHali: 'normal',
    eylem: 'Motor kütüğü ile çalıştırma yolu karşılaştırılır',
    beklenenSonuc: 'Kütükteki her motor koşturulabilir; ölü kayıt yoktur',
    beklenenEkran: 'Motor adı kütükte tekrar etmez',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['ENGINE', 'DOMAIN'],
  },
  {
    id: 'YON-MOT-004', alan: 'Yönetim konsolu', rota: '—', eksen: 'akis',
    amac: 'Motorun insan onayı olmadan iş açmaması',
    rol: 'sistem (motor)', kapsam: 'kurum geneli',
    onkosul: 'Uyumsuz ve kritik bir madde var', veriHali: 'normal',
    eylem: 'Boşluk–aksiyon motoru koşar',
    beklenenSonuc: 'Proje ADAYI üretir; insan onayı olmadan projeye DÖNMEZ',
    beklenenEkran: 'Aday listesi ayrı durur',
    beklenenIz: 'Aday kaydı', beklenenBildirim: 'Görev',
    katmanlar: ['ENGINE', 'WORKFLOW'],
  },
  {
    id: 'SAG-VKL-001', alan: 'Sağlık', rota: '/saglik', eksen: 'veri',
    amac: 'Aktarılan verinin kendi kalitesinin denetlenmesi',
    rol: 'platform yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Entegrasyon tabloları boş', veriHali: 'yok',
    eylem: 'Veri kalitesi motoru koşar',
    beklenenSonuc: 'Aktarım kuralları YANLIŞ POZİTİF üretmez',
    beklenenEkran: 'Sessizlik de bir sözleşmedir ve ölçülür',
    beklenenIz: 'Koşu kaydı', beklenenBildirim: 'yok',
    katmanlar: ['ENGINE'],
  },
  {
    id: 'SAG-VKL-002', alan: 'Sağlık', rota: '/saglik', eksen: 'veri',
    amac: 'Ağda görülen sahipsiz cihazın bulguya dönmesi',
    rol: 'platform yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Eşleşen varlığın sahibi yok', veriHali: 'kısmi',
    eylem: 'Veri kalitesi motoru koşar',
    beklenenSonuc: 'Bulgu VARLIK başına açılır, gözlem başına DEĞİL',
    beklenenEkran: 'Aynı cihaz için beş bulgu üretilmez',
    beklenenIz: 'Bulgu', beklenenBildirim: 'Veri kalitesi bulgusu',
    katmanlar: ['ENGINE', 'DOMAIN'],
  },
  {
    id: 'SIS-KPS-003', alan: 'Sistem', rota: '—', eksen: 'yetki',
    amac: 'Kapsam kapısının hiçbir eylemde atlanmaması',
    rol: 'geliştirici / denetçi', kapsam: 'kurum geneli',
    onkosul: '—', veriHali: 'normal',
    eylem: 'Bütün sunucu eylemleri taranır',
    beklenenSonuc: 'Kapsam sonrası bildiren her eylem ikinci aşamayı GERÇEKTEN çağırır',
    beklenenEkran: '—',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['RBAC', 'SCOPE'],
  },
];

/* ── Dördüncü dalga: görsel kapı ve kalan aykırı hâller ─────────────── */

export const PLATFORM_SENARYOLARI_4: Senaryo[] = [
  {
    id: 'SIS-GOC-001', alan: 'Sistem', rota: '—', eksen: 'veri',
    amac: 'Sürüm yükseltmesinin veri kaybettirmemesi',
    rol: 'platform yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Yeni bir göç uygulanacak', veriHali: 'normal',
    eylem: 'Göçler uygulanır ve şema doğrulanır',
    beklenenSonuc: 'Tablo ve tetikleyici sayısı korunur; yabancı anahtar temizdir',
    beklenenEkran: '—',
    beklenenIz: 'Göç kaydı', beklenenBildirim: 'yok',
    katmanlar: ['MIGRATION'],
  },
  {
    id: 'SIS-GOC-002', alan: 'Sistem', rota: '—', eksen: 'veri',
    amac: 'Denetim izinin sonradan değiştirilememesi',
    rol: 'güvenlik denetçisi', kapsam: 'kurum geneli',
    onkosul: 'Kanıt sürüm geçmişi yazılmış', veriHali: 'normal',
    eylem: 'Geçmişi değiştirmeyi ya da silmeyi dener',
    beklenenSonuc: 'Veritabanı tetikleyicisi REDDEDER',
    beklenenEkran: '—',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['MIGRATION', 'SERVER'],
  },
  {
    id: 'SIS-GRS-001', alan: 'Sistem', rota: '—', eksen: 'arayuz',
    amac: 'Ekranların görsel dilinin sürüklenmemesi',
    rol: 'tasarım denetçisi', kapsam: 'kurum geneli',
    onkosul: '—', veriHali: 'normal',
    eylem: 'Tasarım kapısı koşturulur',
    beklenenSonuc: 'Kontrast, font ve eski tasarım izi kusuru SIFIRDIR',
    beklenenEkran: 'Tek palet; açık temaya geçiş yok',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['VISUAL'],
  },
  {
    id: 'SIS-GRS-002', alan: 'Sistem', rota: '—', eksen: 'arayuz',
    amac: 'Uzun Türkçe metnin yerleşimi bozmaması',
    rol: 'son kullanıcı', kapsam: 'kendi kapsamı',
    onkosul: 'Kayıt adları uzun', veriHali: 'yüksek',
    eylem: 'Dar bantta ekranları gezer',
    beklenenSonuc: 'Kırpılan kritik bilgi ve yatay taşma SIFIRDIR',
    beklenenEkran: 'Geniş içerik kendi kabında kayar',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['VISUAL', 'RESPONSIVE'],
  },
  {
    id: 'BLD-KTU-003', alan: 'Bildirim', rota: '/bildirimler', eksen: 'veri',
    amac: 'Okunmamış bildirimi olmayan kullanıcının rozet görmemesi',
    rol: 'herhangi bir kullanıcı', kapsam: 'kendi kutusu',
    onkosul: 'Hiç okunmamış bildirim yok', veriHali: 'yok',
    eylem: 'Kabuktaki sayaca bakar',
    beklenenSonuc: '"En eski okunmamış" SIFIR GÜN değil, ölçülmedi (null)',
    beklenenEkran: 'Sıfırda rozet ÇİZİLMEZ',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'UI'],
  },
  {
    id: 'RAP-URT-003', alan: 'Rapor', rota: '/raporlar', eksen: 'veri',
    amac: 'Yarısı ölçülmemiş bir hücreye güvenmemek',
    rol: 'uyum yöneticisi', kapsam: 'kendi santrali',
    onkosul: 'Hücrenin yarısından çoğu değerlendirilmemiş',
    veriHali: 'bilinmiyor',
    eylem: 'Rapor matrisine bakar',
    beklenenSonuc: 'Yüzde artık hücreyi TEMSİL ETMEZ ve hücre bilinmeyen işareti alır',
    beklenenEkran: 'Bilinmeyen oranı ayrıca yazılır',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN'],
  },
  {
    id: 'ESL-PRF-003', alan: 'Eşleme', rota: '/esleme', eksen: 'veri',
    amac: 'Kaynağın göndermediği alanın sıfır sanılmaması',
    rol: 'platform yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Alan kaynaktan hiç gelmiyor', veriHali: 'bilinmiyor',
    eylem: 'Eşlemeyi önizler',
    beklenenSonuc: 'Gelmeyen alan SIFIR değil BİLİNMEYENdir',
    beklenenEkran: 'Varsayılan bir ÖLÇÜM DEĞİLDİR',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'INTEGRATION'],
  },
  {
    id: 'YRD-SOR-002', alan: 'Yardım', rota: '/yardim', eksen: 'arayuz',
    amac: 'Kısayol katmanının yazı yazarken açılmaması',
    rol: 'herhangi bir kullanıcı', kapsam: 'kendi kapsamı',
    onkosul: 'Kullanıcı bir metin alanında yazıyor', veriHali: 'kısmi',
    eylem: 'Soru işaretine basar',
    beklenenSonuc: 'Katman AÇILMAZ — yazılan metin bölünmez',
    beklenenEkran: 'Yazı almayan öğelerde tetiklenir',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['UI', 'ACCESSIBILITY'],
  },
  {
    id: 'OPR-DEG-003', alan: 'Operasyon', rota: '/operasyon', eksen: 'akis',
    amac: 'Geri almanın bir aşama sanılmaması',
    rol: 'operasyon sorumlusu', kapsam: 'kendi santrali',
    onkosul: 'Değişiklik geri alındı', veriHali: 'kısmi',
    eylem: 'Aşama şeridine bakar',
    beklenenSonuc: 'Geri alma döngünün ADIMI DEĞİLDİR — indeksi yoktur',
    beklenenEkran: 'Kapanış hem doğrulanmayı hem geri alınmayı kapsar',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN'],
  },
];

/* ── Beşinci dalga: yetki kapısının kendisi ──────────────────────────
   Bu dört senaryo bir SABOTAJ koşusunun bulduğu boşluktan doğdu: ilk
   kapının izin kontrolü silindiğinde test paketi kırılmıyordu, çünkü
   ölçüm hep ikinci aşamadan geçiyordu. Kapı artık kendi başına ölçülür. */

export const PLATFORM_SENARYOLARI_5: Senaryo[] = [
  {
    id: 'SIS-KPS-004', alan: 'Sistem', rota: '—', eksen: 'yetki',
    amac: 'Oturumsuz bir çağrının hiçbir şey yapamaması',
    rol: 'kimliksiz ziyaretçi', kapsam: 'yok',
    onkosul: 'Oturum yok', veriHali: 'yok',
    eylem: 'Bir sunucu eylemini doğrudan çağırır',
    beklenenSonuc: 'Kapı "oturum gerekli" diye reddeder',
    beklenenEkran: '—',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'RBAC'],
  },
  {
    id: 'SIS-KPS-005', alan: 'Sistem', rota: '—', eksen: 'yetki',
    amac: 'Okuma yetkisinin yazmaya yetmemesi',
    rol: 'salt okuyucu', kapsam: 'kurum geneli',
    onkosul: 'Rolün modülde yazma izni yok', veriHali: 'normal',
    eylem: 'Bir yazma eylemi çağırır',
    beklenenSonuc: 'İlk kapı TEK BAŞINA reddeder — ikinci aşamaya kalmaz',
    beklenenEkran: 'Yazma yüzeyi hiç açılmaz',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'RBAC'],
  },
  {
    id: 'SIS-KPS-006', alan: 'Sistem', rota: '—', eksen: 'yetki',
    amac: 'Bir modüldeki yetkinin başka modülü açmaması',
    rol: 'uyum uzmanı', kapsam: 'kurum geneli',
    onkosul: 'Yetki yalnız uyum modülüne verilmiş', veriHali: 'normal',
    eylem: 'Envanter modülünde yazma dener',
    beklenenSonuc: 'Reddedilir',
    beklenenEkran: 'Modül kısıtı diğer modülleri kapatır',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'RBAC'],
  },
  {
    id: 'SIS-KPS-007', alan: 'Sistem', rota: '—', eksen: 'yetki',
    amac: 'İkinci aşamanın kendi mesajını vermesi',
    rol: 'BT yöneticisi', kapsam: 'tek santral',
    onkosul: 'Kaydın santrali kullanıcının kapsamı dışında',
    veriHali: 'normal',
    eylem: 'Kayıt okunduktan sonra kapsam kapısı sorulur',
    beklenenSonuc: 'Eyleme özel mesajla reddedilir',
    beklenenEkran: 'Kullanıcı neyin eksik olduğunu okur',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'SCOPE'],
  },
];
