import type { Senaryo } from './tipler';

/* Uyum alanının senaryoları: uyum çerçeveleri, süreçler, bulgu/CAPA,
   risk, denetim, kanıt, proje, gözden geçirme, saklama, dış denetçi
   erişimi, doküman ve eğitim.

   Bu alanın değişmezi: bir maddenin "uygulanamaz" olması ile
   "değerlendirilmemiş" olması AYNI ŞEY DEĞİLDİR ve hiçbir ekran ikisini
   aynı renge boyamaz. */

export const UYUM_SENARYOLARI: Senaryo[] = [
  /* ── Uyum çerçevesi ─────────────────────────────────────────────── */
  {
    id: 'UYU-CRC-001', alan: 'Uyum', rota: '/uyum', eksen: 'veri',
    amac: 'Kurumun hangi çerçevede nerede olduğunu görmek',
    rol: 'uyum uzmanı', kapsam: 'kendi tesisi',
    onkosul: 'En az bir regülasyon tanımlı', veriHali: 'normal',
    eylem: 'Uyum ekranını açar',
    beklenenSonuc: 'Çerçeve başına uyum oranı ve açık madde sayısı görünür',
    beklenenEkran: 'Oran payda ile birlikte; çıplak yüzde değil',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'UI'],
  },
  {
    id: 'UYU-CRC-002', alan: 'Uyum', rota: '/uyum', eksen: 'veri',
    amac: 'Ölçülmemiş maddenin uyumlu sanılmaması',
    rol: 'uyum uzmanı', kapsam: 'kendi tesisi',
    onkosul: 'Bazı maddeler hiç değerlendirilmemiş', veriHali: 'bilinmiyor',
    eylem: 'Uyum oranına bakar',
    beklenenSonuc: 'Değerlendirilmemiş madde paydada kalır, payda sayılmaz',
    beklenenEkran: 'Bilinmeyen dilimi ayrı taramayla çizilir',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'UI'],
  },
  {
    id: 'UYU-CRC-003', alan: 'Uyum', rota: '/uyum/[cerceve]', eksen: 'veri',
    amac: 'Bir çerçevenin maddelerini tek tek incelemek',
    rol: 'uyum uzmanı', kapsam: 'kendi tesisi',
    onkosul: 'Çerçeve kodu geçerli', veriHali: 'normal',
    eylem: 'Çerçeve detayını açar',
    beklenenSonuc: 'Maddeler hiyerarşisiyle listelenir',
    beklenenEkran: 'Madde durumu ve kanıt bağı görünür',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'UI'],
  },
  {
    id: 'UYU-UYG-001', alan: 'Uyum', rota: '/uyum', eksen: 'veri',
    amac: 'Tesise uygulanmayan maddenin kusur sayılmaması',
    rol: 'uyum uzmanı', kapsam: 'kendi tesisi',
    onkosul: 'Tesis profiline göre madde uygulanamaz', veriHali: 'kısmi',
    eylem: 'Uygulanabilirlik hesabına bakar',
    beklenenSonuc: 'Madde payda dışına çıkar; kusur olarak sayılmaz',
    beklenenEkran: '"Uygulanamaz" ayrı bir durum olarak yazılır',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'ENGINE'],
  },
  {
    id: 'UYU-UYG-002', alan: 'Uyum', rota: '/uyum', eksen: 'veri',
    amac: 'Profili olmayan tesiste hesabın uydurulmaması',
    rol: 'uyum uzmanı', kapsam: 'kendi tesisi',
    onkosul: 'Tesisin profili yok', veriHali: 'yok',
    eylem: 'Uygulanabilirlik hesabına bakar',
    beklenenSonuc: 'Hesap yapılamaz ve bu AÇIKÇA yazılır',
    beklenenEkran: '"Hesaplanamaz" cümlesi; sıfır DEĞİL',
    beklenenIz: 'yazma yok', beklenenBildirim: 'Veri kalitesi bulgusu',
    katmanlar: ['DOMAIN', 'ENGINE'],
  },
  {
    id: 'UYU-OLC-001', alan: 'Uyum', rota: '/surecler/[id]', eksen: 'akis',
    amac: 'Bir maddeyi değerlendirip durumunu güncellemek',
    rol: 'uyum uzmanı', kapsam: 'kendi tesisi',
    onkosul: 'Kullanıcı yazma yetkili', veriHali: 'normal',
    eylem: 'Madde durumunu değiştirir',
    beklenenSonuc: 'Ölçüm kaydedilir',
    beklenenEkran: 'Yeni durum ve ölçen kişi görünür',
    beklenenIz: 'Uyum ölçümü · guncelleme',
    beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'RBAC', 'WORKFLOW'],
  },
  {
    id: 'UYU-OLC-002', alan: 'Uyum', rota: '/surecler/[id]', eksen: 'yetki',
    amac: 'Kapsam dışı sürecin ölçülememesi',
    rol: 'uyum uzmanı', kapsam: 'tek tesis',
    onkosul: 'Süreç başka tesise ait', veriHali: 'normal',
    eylem: 'Ölçüm kaydetmeyi dener',
    beklenenSonuc: 'Kapsam kapısı reddeder',
    beklenenEkran: 'Süreç listede görünmez',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'SCOPE'],
  },
  {
    id: 'UYU-SHP-001', alan: 'Uyum', rota: '/uyum', eksen: 'akis',
    amac: 'Her maddenin bir sorumlusu olması',
    rol: 'uyum yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Maddenin sahibi yok', veriHali: 'kısmi',
    eylem: 'Sahiplik atar',
    beklenenSonuc: 'Sahiplik kaydedilir',
    beklenenEkran: 'Sahipsiz madde sayısı düşer',
    beklenenIz: 'Sahiplik · olusturma', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'DOMAIN'],
  },

  /* ── Bulgu ve CAPA ──────────────────────────────────────────────── */
  {
    id: 'BUL-LST-001', alan: 'Bulgu', rota: '/bulgular', eksen: 'veri',
    amac: 'Açık bulguların hangisinin acil olduğunu görmek',
    rol: 'uyum uzmanı', kapsam: 'kendi tesisi',
    onkosul: 'Açık bulgular var', veriHali: 'normal',
    eylem: 'Bulgular ekranını açar',
    beklenenSonuc: 'Son tarihi geçen ve yüksek şiddetli bulgular önde',
    beklenenEkran: 'Sürükleyici satırlar kuyruğa inmez',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'UI'],
  },
  {
    id: 'BUL-LST-002', alan: 'Bulgu', rota: '/bulgular', eksen: 'veri',
    amac: 'Hiç bulgu yokken bunun iyi haber olduğunu anlamak',
    rol: 'uyum uzmanı', kapsam: 'kendi tesisi',
    onkosul: 'Kapsamda açık bulgu yok', veriHali: 'yok',
    eylem: 'Bulgular ekranını açar',
    beklenenSonuc: 'Boş durum "denetlenmedi" ile karıştırılmaz',
    beklenenEkran: 'Boş ilk-durum cümlesi',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'UI'],
  },
  {
    id: 'BUL-DTY-001', alan: 'Bulgu', rota: '/bulgular/[id]', eksen: 'akis',
    amac: 'Bir bulgunun geçmişini ve kanıtını görmek',
    rol: 'uyum uzmanı', kapsam: 'kendi tesisi',
    onkosul: 'Bulgu kullanıcının kapsamında', veriHali: 'normal',
    eylem: 'Bulgu detayını açar',
    beklenenSonuc: 'Zaman çizelgesi, kanıtlar ve aksiyonlar görünür',
    beklenenEkran: 'Denetim izi kronolojik',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'UI'],
  },
  {
    id: 'BUL-DTY-002', alan: 'Bulgu', rota: '/bulgular/[id]', eksen: 'yetki',
    amac: 'Kapsam dışı bulgunun görülememesi',
    rol: 'uyum uzmanı', kapsam: 'tek tesis',
    onkosul: 'Bulgu başka tesise ait', veriHali: 'normal',
    eylem: 'Doğrudan adresle açmayı dener',
    beklenenSonuc: 'Kayıt bulunamaz olarak döner',
    beklenenEkran: 'Bulunamadı sayfası',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SCOPE', 'UI'],
  },
  {
    id: 'BUL-KAP-001', alan: 'Bulgu', rota: '/bulgular/[id]', eksen: 'akis',
    amac: 'Düzeltilen bulgunun kanıtla kapatılması',
    rol: 'uyum uzmanı', kapsam: 'kendi tesisi',
    onkosul: 'Bulgunun doğrulama kanıtı yok', veriHali: 'kısmi',
    eylem: 'Bulguyu kapatmayı dener',
    beklenenSonuc: 'Doğrulama kanıtı olmadan kapatılamaz',
    beklenenEkran: 'Eksik kanıt açıkça yazılır',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'WORKFLOW'],
  },
  {
    id: 'BUL-KAP-002', alan: 'Bulgu', rota: '/bulgular/[id]', eksen: 'akis',
    amac: 'Aynı kök nedenin tekrarının görülmesi',
    rol: 'uyum yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Aynı kök nedenle bulgu tekrar açılmış', veriHali: 'yinelenen',
    eylem: 'Tekrar motoru koşar',
    beklenenSonuc: 'Tekrar işaretlenir ve görev açılır',
    beklenenEkran: 'Tekrar rozeti',
    beklenenIz: 'Aktivite kaydı', beklenenBildirim: 'Görev',
    katmanlar: ['ENGINE', 'WORKFLOW'],
  },

  /* ── Risk ───────────────────────────────────────────────────────── */
  {
    id: 'RSK-LST-001', alan: 'Risk', rota: '/riskler', eksen: 'veri',
    amac: 'Artık riski yüksek kayıtları görmek',
    rol: 'risk sorumlusu', kapsam: 'kendi tesisi',
    onkosul: 'Riskler tanımlı', veriHali: 'normal',
    eylem: 'Riskler ekranını açar',
    beklenenSonuc: 'Artık risk sıralamasıyla listelenir',
    beklenenEkran: 'Eşikler konsoldan gelir',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'UI'],
  },
  {
    id: 'RSK-LST-002', alan: 'Risk', rota: '/riskler', eksen: 'veri',
    amac: 'Değerlendirilmemiş riskin sıfır sayılmaması',
    rol: 'risk sorumlusu', kapsam: 'kendi tesisi',
    onkosul: 'Artık risk hesaplanmamış', veriHali: 'bilinmiyor',
    eylem: 'Listeye bakar',
    beklenenSonuc: '"Hesaplanmadı" yazılır; 0 DEĞİL',
    beklenenEkran: 'Bilinmeyen işaretçisi',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN'],
  },
  {
    id: 'RSK-DTY-001', alan: 'Risk', rota: '/riskler/[id]', eksen: 'akis',
    amac: 'Riski bir kontrole ve bulguya bağlamak',
    rol: 'risk sorumlusu', kapsam: 'kendi tesisi',
    onkosul: 'Kullanıcı yazma yetkili', veriHali: 'normal',
    eylem: 'Risk detayında kontrol bağlar',
    beklenenSonuc: 'Zincir kurulur',
    beklenenEkran: 'Risk → kontrol → bulgu zinciri görünür',
    beklenenIz: 'Risk · guncelleme', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'DOMAIN'],
  },

  /* ── Denetim ────────────────────────────────────────────────────── */
  {
    id: 'DEN-LST-001', alan: 'Denetim', rota: '/denetimler', eksen: 'veri',
    amac: 'Planlanan ve süren denetimleri görmek',
    rol: 'uyum yöneticisi', kapsam: 'kendi tesisi',
    onkosul: 'Denetimler tanımlı', veriHali: 'normal',
    eylem: 'Denetimler ekranını açar',
    beklenenSonuc: 'Aşamasıyla birlikte listelenir',
    beklenenEkran: 'Aşama şeridi',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'UI'],
  },
  {
    id: 'DEN-ASM-001', alan: 'Denetim', rota: '/denetimler/[id]', eksen: 'akis',
    amac: 'Denetimi bir sonraki aşamaya taşımak',
    rol: 'uyum yöneticisi', kapsam: 'kendi tesisi',
    onkosul: 'Aşamanın zorunlu kanıtı eksik', veriHali: 'kısmi',
    eylem: 'Aşamayı ilerletmeyi dener',
    beklenenSonuc: 'Zorunlu kanıt olmadan ilerlemez',
    beklenenEkran: 'Eksik kanıt listelenir',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'WORKFLOW'],
  },
  {
    id: 'DEN-ASM-002', alan: 'Denetim', rota: '/denetimler/[id]', eksen: 'yetki',
    amac: 'Denetim kapsamının tesisle sınırlı kalması',
    rol: 'uyum uzmanı', kapsam: 'tek tesis',
    onkosul: 'Denetim başka tesise ait', veriHali: 'normal',
    eylem: 'Aşama değiştirmeyi dener',
    beklenenSonuc: 'Reddedilir',
    beklenenEkran: 'Denetim listede yok',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'SCOPE'],
  },

  /* ── Kanıt ──────────────────────────────────────────────────────── */
  {
    id: 'KNT-LST-001', alan: 'Kanıt', rota: '/kanitlar', eksen: 'veri',
    amac: 'Tazeliği geçmiş kanıtları bulmak',
    rol: 'uyum uzmanı', kapsam: 'kendi tesisi',
    onkosul: 'Kanıt tazelik eşiği aşılmış', veriHali: 'bayat',
    eylem: 'Kanıtlar ekranını açar',
    beklenenSonuc: 'Bayat kanıt ayrı işaretlenir',
    beklenenEkran: 'Eşik konsoldan gelir',
    beklenenIz: 'yazma yok', beklenenBildirim: 'Görev',
    katmanlar: ['DOMAIN', 'ENGINE'],
  },
  {
    id: 'KNT-YUK-001', alan: 'Kanıt', rota: '/kanitlar', eksen: 'akis',
    amac: 'Bir kanıt belgesini yüklemek',
    rol: 'uyum uzmanı', kapsam: 'kendi tesisi',
    onkosul: 'Kullanıcı yazma yetkili', veriHali: 'normal',
    eylem: 'Kanıt ekler',
    beklenenSonuc: 'Kanıt kaydedilir ve özeti alınır',
    beklenenEkran: 'Kanıt listesinde görünür',
    beklenenIz: 'Kanit · olusturma', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'RBAC'],
  },
  {
    id: 'KNT-YUK-002', alan: 'Kanıt', rota: '/kanitlar', eksen: 'yetki',
    amac: 'Kapsam dışı kanıtın görülmemesi',
    rol: 'uyum uzmanı', kapsam: 'tek tesis',
    onkosul: 'Kanıt başka tesise ait', veriHali: 'normal',
    eylem: 'Kanıt listesine bakar',
    beklenenSonuc: 'Kayıt listede yoktur',
    beklenenEkran: 'Sayaçlar da kapsamla sınırlı',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SCOPE', 'DOMAIN'],
  },
  {
    id: 'KNT-SHP-001', alan: 'Kanıt', rota: '/kanitlar', eksen: 'veri',
    amac: 'Sahipsiz kanıtın yenileme sorumlusunun bulunması',
    rol: 'uyum yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Kanıtın sahibi de yükleyeni de yok', veriHali: 'kısmi',
    eylem: 'Veri kalitesi motoru koşar',
    beklenenSonuc: 'Sahipsiz kanıt bulgusu açılır',
    beklenenEkran: 'Sağlık ekranında görünür',
    beklenenIz: 'Bulgu', beklenenBildirim: 'Veri kalitesi bulgusu',
    katmanlar: ['ENGINE', 'DOMAIN'],
  },
  {
    id: 'KNT-PKT-001', alan: 'Kanıt', rota: '/raporlar/kanit-paketi',
    eksen: 'akis',
    amac: 'Denetçiye verilecek kanıt paketini hazırlamak',
    rol: 'uyum yöneticisi', kapsam: 'kendi tesisi',
    onkosul: 'Kanıtlar seçili', veriHali: 'normal',
    eylem: 'Paket üretir',
    beklenenSonuc: 'Paket üretilir ve içindekiler listelenir',
    beklenenEkran: 'İmza yoksa paket "imzasız" der',
    beklenenIz: 'Paket kaydı', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'DOMAIN'],
  },
  {
    id: 'KNT-PKT-002', alan: 'Kanıt', rota: '/raporlar/kanit-paketi',
    eksen: 'entegrasyon',
    amac: 'İmzasız paketin imzalı gibi görünmemesi',
    rol: 'uyum yöneticisi', kapsam: 'kendi tesisi',
    onkosul: 'İmzalama altyapısı bağlı değil', veriHali: 'yok',
    eylem: 'Paket üretir',
    beklenenSonuc: 'Paket "imzasız" olarak işaretlenir',
    beklenenEkran: 'Bağlı değil cümlesi ve ürünün ne yaptığı yazılı',
    beklenenIz: 'Paket kaydı', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'INTEGRATION'],
  },

  /* ── R10 · Olay → mevzuat bildirimi ─────────────────────────────── */
  {
    id: 'OLY-BIL-001', alan: 'Olay', rota: '/olaylar', eksen: 'akis',
    amac: 'Bir olaydan doğan HER mevzuat bildirimini ayrı ayrı görmek ve göndermek',
    rol: 'uyum yöneticisi', kapsam: 'kendi kapsamı',
    onkosul: 'Şiddeti eşiği aşan açık bir olay ve birden çok aktif yükümlülük var',
    veriHali: 'normal',
    eylem: 'Bildirim süresi motoru koşar (`bildirimSuresi.bildirimSurelerini`);'
      + ' insan çekmeceden "Gönderildi olarak işaretle" der'
      + ' (`bildirimKaydi.bildirimGonderildiIsaretle`)',
    beklenenSonuc: 'Uyan her yükümlülük için AYRI bir BildirimKaydi taslağı açılır'
      + ' (en kısa süreli seçilmez); ikinci koşuda ikinci taslak AÇILMAZ;'
      + ' gönderim REFERANS NUMARASI olmadan reddedilir',
    beklenenEkran: 'Çekmecede her merci için ayrı satır: durum · geri sayım ·'
      + ' kanal notu · referans numarası',
    beklenenIz: 'BildirimKaydi · guncelleme (durum: Taslak→Gönderildi, gerekçede referans no)',
    beklenenBildirim: 'Görev (son_tarih) — süre daralınca ya da geçince',
    katmanlar: ['SERVER', 'DOMAIN', 'UI', 'WORKFLOW'],
  },
  {
    id: 'OLY-BIL-002', alan: 'Olay', rota: '/olaylar', eksen: 'veri',
    amac: 'Süresi mevzuatta BELİRLENMEMİŞ bir yükümlülükte saat uydurmamak',
    rol: 'uyum yöneticisi', kapsam: 'kendi kapsamı',
    onkosul: 'Yükümlülüğün `sureSaat` alanı BOŞ (7545 md. 7 "gecikmeksizin")',
    veriHali: 'kısmi',
    eylem: 'Motor koşar ve olayın üstünden yüz saat geçmiştir',
    beklenenSonuc: 'Kayıt açılır ama `sonTarih` NULL kalır; `suresi_gecti` ASLA'
      + ' yazılmaz — geçecek bir süre yoktur. Sıfır saat ile süresiz aynı şey değildir',
    beklenenEkran: 'Geri sayım GÖSTERİLMEZ: "Süre mevzuatta belirlenmedi" yazar ve'
      + ' satır BİLİNMEYEN sınıfındadır (yeşil değil)',
    beklenenIz: 'yazma yok (durum değişmedi)', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'DOMAIN', 'UI'],
  },
  {
    id: 'OLY-BIL-003', alan: 'Olay', rota: '/olaylar', eksen: 'yetki',
    amac: 'Motorun bir bildirimi "gönderildi" diye işaretlemesini engellemek',
    rol: 'sistem (motor)', kapsam: 'kurum geneli',
    onkosul: 'Gönderilmiş bir kayıt var ve süresi geçmiş', veriHali: 'çelişen',
    eylem: 'Motor yeniden koşar',
    beklenenSonuc: 'Motor kapalı kayda DOKUNMAZ; yazabileceği durumlar yalnız'
      + ' `taslak` ve `suresi_gecti`tir. `gonderildi` · `teyit_alindi` ·'
      + ' `uygulanmaz` insan kararıdır ve bekçi motor dosyalarını metin olarak tarar',
    beklenenEkran: 'Kayıt "Gönderildi" olarak kalır',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'DOMAIN', 'WORKFLOW'],
  },
  {
    id: 'OLY-BIL-004', alan: 'Olay', rota: '/olaylar', eksen: 'yetki',
    amac: 'Gönderilmemiş bir bildirimin "gönderildi" görünmesini engellemek',
    rol: 'uyum yöneticisi', kapsam: 'kendi kapsamı',
    onkosul: 'Açık bir bildirim taslağı var', veriHali: 'kısmi',
    eylem: 'İnsan "Gönderildi olarak işaretle" der ama referans alanını BOŞ bırakır'
      + ' (`bildirimKaydi.bildirimGonderildiIsaretle`)',
    beklenenSonuc: 'İstek REDDEDİLİR ve kayıt DEĞİŞMEZ. Referansı olmayan bir'
      + ' gönderim denetimde doğrulanamaz: mercinin kütüğüyle eşleştirilecek tek'
      + ' bağ odur. Referans verilince geçer ve denetim izine referans YAZILIR',
    beklenenEkran: 'Hata satırı alanın altında; kayıt hâlâ taslak durumunda',
    beklenenIz: 'red: yazma yok · kabul: BildirimKaydi · guncelleme (gerekçede referans no)',
    beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'DOMAIN', 'UI'],
  },

  /* ── R12 · Denetim formları ─────────────────────────────────────── */
  {
    id: 'DNT-FRM-001', alan: 'Denetim', rota: '/raporlar/denetim-formlari',
    eksen: 'akis',
    amac: 'Denetçiye verilecek öz denetim formunu üretmek — hiçbir hücresi boş olmadan',
    rol: 'denetim okuma yetkili', kapsam: 'kendi kapsamı',
    onkosul: 'Kapsamda kontrol kaydı var', veriHali: 'normal',
    eylem: 'Satır seçilir, form türü seçilir, "Formu üret ve indir"e basılır'
      + ' (`denetimFormu.denetimFormuUretEylem`)',
    beklenenSonuc: 'CSV ve XLSX birlikte iner; boş hücre sayısı SIFIRDIR ve'
      + ' ölçülmemiş her hücre "Değerlendirilmedi" der (bilinmeyen ≠ sıfır);'
      + ' formül enjeksiyonu kalkanı iki biçimde de uygulanır',
    beklenenEkran: 'Üretimin ölçümü çekmecede kalır: satır · hücre · boş hücre 0'
      + ' · ölçülmedi sayısı · inen dosya adları',
    beklenenIz: 'DenetimFormu kaydı (satır · hücre · boş · ölçülmedi sayılarıyla)',
    beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'DOMAIN', 'UI'],
  },
  {
    id: 'DNT-FRM-002', alan: 'Denetim', rota: '/raporlar/denetim-formlari',
    eksen: 'arayuz',
    amac: 'Gerekçesiz kapsam-dışı kararı denetçiye GİTMEDEN ÖNCE görünür olsun;'
      + ' gerekçe uydurulmasın',
    rol: 'denetim okuma yetkili',
    kapsam: '`/raporlar/denetim-formlari` · satır seçimi paneli (çekmece) · boş hâl',
    onkosul: 'Bir kontrol kapsam dışı bırakılmış ama sebebi yazılmamış',
    veriHali: 'kısmi',
    eylem: 'Ekran açılır; kusurlu satır seçilir; kapsamda hiç kayıt yokken de açılır',
    beklenenSonuc: 'Kusurlu satır listenin ÜSTÜNDE ve `bd` kenarlı; hücre'
      + ' "Kapsam dışı · GEREKÇE YOK" der ve uydurulmuş bir sebep cümlesi taşımaz;'
      + ' boş hâl bir sonraki işi söyler (uyum süreçleri bağı)',
    beklenenEkran: 'Başlıkta kaç kapsamda gerekçesiz kapsam dışı olduğu yazılı;'
      + ' dipnot bu sayının ANLAMINI söyler',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['UI', 'DOMAIN'],
  },
  {
    id: 'DNT-FRM-003', alan: 'Denetim', rota: '/raporlar/denetim-formlari',
    eksen: 'yetki',
    amac: 'Dış denetçi yalnız KENDİ kapsamının formunu indirebilsin;'
      + ' kapsam dışı istek sessizce daraltılmasın',
    rol: 'dış denetçi', kapsam: 'DenetciErisimi kapsamı',
    onkosul: 'Denetçi erişimi açık ve kapsamı iki kapsam öğesini içeriyor',
    veriHali: 'normal',
    eylem: 'Kapsam dışı bir kapsam öğesi için form istenir',
    beklenenSonuc: 'İstek REDDEDİLİR (sessizce daraltılmaz); kaç öğenin dışarıda'
      + ' kaldığı söylenir, hangisi olduğu söylenmez',
    beklenenEkran: 'Listeye kapsam dışı öğe hiç girmez — ekranda gösterip eylemde'
      + ' reddetmek olmayan bir düğme göstermek olurdu',
    beklenenIz: 'DenetimFormu red kaydı', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'DOMAIN'],
  },

  /* ── Proje / CAPA ───────────────────────────────────────────────── */
  {
    id: 'PRJ-LST-001', alan: 'Proje', rota: '/projeler', eksen: 'veri',
    amac: 'Açık aksiyonların durumunu görmek',
    rol: 'proje sorumlusu', kapsam: 'kendi tesisi',
    onkosul: 'Projeler tanımlı', veriHali: 'normal',
    eylem: 'Projeler ekranını açar',
    beklenenSonuc: 'Durum ve son tarihle listelenir',
    beklenenEkran: 'Geciken proje ayrı işaretlenir',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'UI'],
  },
  {
    id: 'PRJ-BAG-001', alan: 'Proje', rota: '/projeler', eksen: 'akis',
    amac: 'Projenin bağımlılığının döngü kurmaması',
    rol: 'proje sorumlusu', kapsam: 'kendi tesisi',
    onkosul: 'Bağımlılık döngü yaratacak', veriHali: 'çelişen',
    eylem: 'Bağımlılık ekler',
    beklenenSonuc: 'Döngü reddedilir',
    beklenenEkran: 'Neden reddedildiği yazılır',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'DOMAIN'],
  },

  /* ── Gözden geçirme · saklama · dış denetçi ─────────────────────── */
  {
    id: 'GZD-DON-001', alan: 'Gözden geçirme', rota: '/gozden-gecirme',
    eksen: 'akis',
    amac: 'Dönemsel gözden geçirmenin zamanında yapılması',
    rol: 'uyum yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Dönem sonu yaklaşmış', veriHali: 'normal',
    eylem: 'Gözden geçirme ekranını açar',
    beklenenSonuc: 'Bekleyen kalemler ve son tarih görünür',
    beklenenEkran: 'Geciken kalem ayrı sayılır',
    beklenenIz: 'yazma yok', beklenenBildirim: 'Görev',
    katmanlar: ['DOMAIN', 'ENGINE'],
  },
  {
    id: 'SAK-SUR-001', alan: 'Saklama', rota: '/saklama', eksen: 'veri',
    amac: 'Hangi kaydın ne kadar saklanacağını görmek',
    rol: 'uyum yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Saklama süresi tanımlanmamış', veriHali: 'yok',
    eylem: 'Saklama ekranını açar',
    beklenenSonuc: 'Süre uydurulmaz; "tanımlanmadı" yazılır',
    beklenenEkran: 'Dayanak alanı boşsa imha önerilmez',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'UI'],
  },
  {
    id: 'DNE-ERS-001', alan: 'Dış denetçi', rota: '/denetci-erisimi',
    eksen: 'yetki',
    amac: 'Dış denetçiye süreli ve sınırlı erişim vermek',
    rol: 'uyum yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Kullanıcı yetkili', veriHali: 'normal',
    eylem: 'Denetçi erişimi tanımlar',
    beklenenSonuc: 'Erişim bitiş tarihiyle açılır',
    beklenenEkran: 'Süresiz erişim verilemez',
    beklenenIz: 'Erişim kaydı', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'RBAC'],
  },
  {
    id: 'DNE-ERS-002', alan: 'Dış denetçi', rota: '/denetci-erisimi',
    eksen: 'yetki',
    amac: 'Dış denetçinin yazma yapamaması',
    rol: 'dış denetçi', kapsam: 'verilen kapsam',
    onkosul: 'Denetçi hesabı aktif', veriHali: 'normal',
    eylem: 'Bir yazma eylemi çağırır',
    beklenenSonuc: 'Reddedilir',
    beklenenEkran: 'Yazma yüzeyleri kapalı',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'RBAC'],
  },

  /* ── Doküman ve eğitim ──────────────────────────────────────────── */
  {
    id: 'DOK-SUR-001', alan: 'Doküman', rota: '/dokumanlar', eksen: 'akis',
    amac: 'Politikanın güncel sürümünü bulmak',
    rol: 'uyum uzmanı', kapsam: 'kurum geneli',
    onkosul: 'Doküman kütüğü dolu', veriHali: 'normal',
    eylem: 'Dokümanlar ekranını açar',
    beklenenSonuc: 'Yürürlükteki sürüm ve onay tarihi görünür',
    beklenenEkran: 'Süresi geçen doküman ayrı işaretlenir',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'UI'],
  },
  {
    id: 'DOK-SUR-002', alan: 'Doküman', rota: '/dokumanlar',
    eksen: 'entegrasyon',
    amac: 'DYS bağlı değilken senkron iddiasında bulunulmaması',
    rol: 'uyum uzmanı', kapsam: 'kurum geneli',
    onkosul: 'Doküman yönetim sistemi bağlı değil', veriHali: 'yok',
    eylem: 'Doküman kaydına bakar',
    beklenenSonuc: 'Sürüm "elle girildi" der; "DYS ile senkron" DEMEZ',
    beklenenEkran: 'Bağlı değil cümlesi',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'INTEGRATION'],
  },
  {
    id: 'EGT-KAT-001', alan: 'Eğitim', rota: '/egitimler', eksen: 'veri',
    amac: 'Kimin hangi eğitimi tamamladığını görmek',
    rol: 'uyum yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Eğitim kayıtları var', veriHali: 'kısmi',
    eylem: 'Eğitimler ekranını açar',
    beklenenSonuc: 'Katılmayan ile kaydı olmayan ayrı sayılır',
    beklenenEkran: '"Kayıt yok" ile "katılmadı" farklı',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'UI'],
  },

  /* ── Mevzuat kaynağı ────────────────────────────────────────────── */
  {
    id: 'MEV-KYN-001', alan: 'Mevzuat', rota: '/regulasyonlar',
    eksen: 'entegrasyon',
    amac: 'Mevzuat değişikliğinden haberdar olmak',
    rol: 'uyum uzmanı', kapsam: 'kurum geneli',
    onkosul: 'Takip edilecek kaynak tanımlanmamış', veriHali: 'yok',
    eylem: 'Regülasyonlar ekranını açar',
    beklenenSonuc: 'Kaynak yoksa "takip edilmiyor" yazılır',
    beklenenEkran: 'Adres ürünle GELMEZ; kurum tanımlar',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'INTEGRATION'],
  },
];

/* ── İkinci dalga: kalan uyum yüzeyleri ─────────────────────────────── */

export const UYUM_SENARYOLARI_2: Senaryo[] = [
  {
    id: 'UYU-SUR-001', alan: 'Uyum', rota: '/regulasyonlar', eksen: 'akis',
    amac: 'Mevzuat yenilendiğinde eski değerlendirmeyi kaybetmemek',
    rol: 'uyum yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Yeni sürüm hazırlanıyor', veriHali: 'normal',
    eylem: 'Regülasyonun yeni sürümünü etkinleştirir',
    beklenenSonuc: 'Eski değerlendirmeler SİLİNMEZ; fark listesi çıkar',
    beklenenEkran: 'Yarım sürüm oluşmaz — kopyalama ya tamdır ya hiç',
    beklenenIz: 'Sürüm · olusturma + fark satırları',
    beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'WORKFLOW', 'CONCURRENCY'],
  },
  {
    id: 'UYU-IST-001', alan: 'Uyum', rota: '/uyum', eksen: 'akis',
    amac: 'Karşılanamayan bir maddeye süreli istisna almak',
    rol: 'uyum uzmanı', kapsam: 'kendi tesisi',
    onkosul: 'Gerekçe kısa ya da bitiş tarihi geçmiş', veriHali: 'çelişen',
    eylem: 'İstisna talep eder',
    beklenenSonuc: 'Reddedilir — süresiz ya da gerekçesiz istisna olmaz',
    beklenenEkran: 'Madde durumu talepten SONRA da aynı kalır',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'DOMAIN'],
  },
  {
    id: 'UYU-IST-002', alan: 'Uyum', rota: '/uyum', eksen: 'akis',
    amac: 'Onaylanan istisnanın maddeyi kapsam dışına alması',
    rol: 'uyum yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'İstisna onay bekliyor', veriHali: 'normal',
    eylem: 'İstisnayı onaylar',
    beklenenSonuc: 'Madde kapsam dışına çıkar; süre dolunca geri döner',
    beklenenEkran: 'Yan etki patlarsa istisna da aktif KALMAZ',
    beklenenIz: 'İstisna + durum + tarihçe + iz birlikte',
    beklenenBildirim: 'Onay merkezine talep',
    katmanlar: ['SERVER', 'WORKFLOW'],
  },
  {
    id: 'UYU-TRN-001', alan: 'Uyum', rota: '/uyum', eksen: 'veri',
    amac: 'Uyumun zaman içinde nereye gittiğini görmek',
    rol: 'uyum yöneticisi', kapsam: 'tek tesis',
    onkosul: 'Aynı gün hem süreç geneli hem tesis kaydı var',
    veriHali: 'yinelenen',
    eylem: 'Eğilim çizgisine bakar',
    beklenenSonuc: 'Aynı gün için tek nokta sayılır; kapsam daraltması korunur',
    beklenenEkran: 'Başka tesisin noktası sızmaz',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'SCOPE'],
  },
  {
    id: 'UYU-BLG-001', alan: 'Uyum', rota: '/uyum', eksen: 'veri',
    amac: 'Bir kontrolü hangi belgenin karşıladığını görmek',
    rol: 'uyum uzmanı', kapsam: 'tek tesis',
    onkosul: 'Belge başka tesise bağlı', veriHali: 'kısmi',
    eylem: 'Matris hücresine bakar',
    beklenenSonuc: 'Belge ÖTEKİ tesisin hücresine SIZMAZ',
    beklenenEkran: 'Kurumsal belge her tesisin hücresine düşer',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'SCOPE'],
  },
  {
    id: 'UYU-PRS-001', alan: 'Uyum', rota: '/prosesler', eksen: 'yetki',
    amac: 'Bir uyum sürecini açmak',
    rol: 'uyum uzmanı', kapsam: 'tek tesis',
    onkosul: 'Süreç başka tesise ait olacak', veriHali: 'normal',
    eylem: 'Süreç açmayı dener',
    beklenenSonuc: 'Reddedilir; süreç başka tesise KAÇIRILAMAZ',
    beklenenEkran: 'Tesis seçimi kapsamla sınırlı',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'SCOPE'],
  },
  {
    id: 'UYU-OLG-001', alan: 'Uyum', rota: '/surecler/[id]', eksen: 'veri',
    amac: 'Bir kontrolün olgunluğunu ölçmek',
    rol: 'uyum uzmanı', kapsam: 'kendi tesisi',
    onkosul: 'Olgunluk hiç ölçülmemiş', veriHali: 'bilinmiyor',
    eylem: 'Olgunluk dağılımına bakar',
    beklenenSonuc: 'Ölçülmemiş `olculmedi`dir; SIFIR ölçülmüş bir sonuçtur',
    beklenenEkran: 'Ortalama diye bir alan YOKTUR',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN'],
  },
  {
    id: 'BUL-ANL-001', alan: 'Bulgu', rota: '/bulgular/[id]', eksen: 'akis',
    amac: 'Kök nedeni yazmadan kritik bulgunun kapanmaması',
    rol: 'uyum uzmanı', kapsam: 'kendi tesisi',
    onkosul: 'Bulgu kritik, analiz yok', veriHali: 'kısmi',
    eylem: 'Bulguyu kapatmayı dener',
    beklenenSonuc: 'Reddedilir; kategori seçmek analiz DEĞİLDİR',
    beklenenEkran: 'Eksik olanın ne olduğu yazılır',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'WORKFLOW'],
  },
  {
    id: 'BUL-UYG-001', alan: 'Bulgu', rota: '/bulgular', eksen: 'akis',
    amac: 'Aynı kusur için ikinci bir bulgu açılmaması',
    rol: 'sistem (motor)', kapsam: 'kurum geneli',
    onkosul: 'Aynı tesis ve kural için açık bulgu var',
    veriHali: 'yinelenen',
    eylem: 'Motor tekrar koşar',
    beklenenSonuc: 'Açık bulgu ÇOĞALTILMAZ',
    beklenenEkran: 'Kapatılmış bulgu koşuyu engellemez',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['ENGINE'],
  },
  {
    id: 'KNT-DEP-001', alan: 'Kanıt', rota: '/kanitlar', eksen: 'entegrasyon',
    amac: 'Yüklenen dosyanın denetimde açılabilmesi',
    rol: 'uyum uzmanı', kapsam: 'kendi tesisi',
    onkosul: 'Dosya diskte değiştirilmiş', veriHali: 'çelişen',
    eylem: 'Kanıt dosyasını okur',
    beklenenSonuc: 'Sessizce sağlam DÖNMEZ; özet doğrulaması düşer',
    beklenenEkran: 'Boş dosya reddedilir',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'INTEGRATION'],
  },
  {
    id: 'KNT-TAZ-001', alan: 'Kanıt', rota: '/ayarlar', eksen: 'yetki',
    amac: 'Kanıt tazelik eşiğini kurumun gerçeğine göre ayarlamak',
    rol: 'kurum yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Eşik B sınıfı bir ayardır', veriHali: 'normal',
    eylem: 'Eşiği doğrudan yazmayı dener',
    beklenenSonuc: 'B sınıfı ayar doğrudan yazılamaz; öneri–onay ister',
    beklenenEkran: 'Konsolda sınıf ve hedef görünür',
    beklenenIz: 'Değişiklik önerisi', beklenenBildirim: 'Onay merkezi',
    katmanlar: ['SERVER', 'RBAC'],
  },
  {
    id: 'DEN-GRV-001', alan: 'Denetim', rota: '/yonetim-tezgahi', eksen: 'yetki',
    amac: 'Bana düşen görevi kapatmak',
    rol: 'görev sorumlusu', kapsam: 'kendi tesisi',
    onkosul: 'Görev başkasına ait', veriHali: 'normal',
    eylem: 'Başkasının görevini kapatmayı dener',
    beklenenSonuc: 'Yazma yetkisi TEK BAŞINA yetmez',
    beklenenEkran: 'Sorumlusu kendi görevini kapatabilir',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'RBAC'],
  },
  {
    id: 'DOK-KTK-001', alan: 'Doküman', rota: '/dokumanlar', eksen: 'akis',
    amac: 'Belgenin yaşam döngüsünün atlanmaması',
    rol: 'uyum uzmanı', kapsam: 'kurum geneli',
    onkosul: 'Belge taslak', veriHali: 'normal',
    eylem: 'Taslağı doğrudan yürürlüğe almayı dener',
    beklenenSonuc: 'Reddedilir — inceleme adımı atlanamaz',
    beklenenEkran: 'Hangi adımın eksik olduğu söylenir',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'WORKFLOW'],
  },
  {
    id: 'DGA-AKT-001', alan: 'Değerlendirme aktarımı',
    rota: '/degerlendirme-aktarim', eksen: 'akis',
    amac: 'Toplu değerlendirmeyi tek seferde almak',
    rol: 'uyum uzmanı', kapsam: 'kendi tesisi',
    onkosul: 'İki kullanıcı aynı anda aktarıyor', veriHali: 'yinelenen',
    eylem: 'Eşzamanlı iki aktarım denemesi yapılır',
    beklenenSonuc: 'Tam biri yazar; kaybeden ize HİÇBİR ŞEY yazmaz',
    beklenenEkran: 'Karara bağlanmış kayıt yeniden karara açılmaz',
    beklenenIz: 'Tek karar satırı', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'CONCURRENCY'],
  },
  {
    id: 'ESL-MTR-001', alan: 'Eşleştirme', rota: '/eslestirme', eksen: 'veri',
    amac: 'Bir maddenin başka çerçevedeki karşılığını görmek',
    rol: 'uyum uzmanı', kapsam: 'kurum geneli',
    onkosul: 'Eşleştirme kayıtları var', veriHali: 'normal',
    eylem: 'Eşleştirme matrisine bakar',
    beklenenSonuc: 'Karşılığı olmayan madde boş bırakılır, uydurulmaz',
    beklenenEkran: 'Bilinmeyen ayrı işaretlenir',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'UI'],
  },
];

/* ── Üçüncü dalga: kalan aykırı hâller ──────────────────────────────── */

export const UYUM_SENARYOLARI_3: Senaryo[] = [
  {
    id: 'GZD-DON-002', alan: 'Gözden geçirme', rota: '/gozden-gecirme',
    eksen: 'veri',
    amac: 'Tarihi geçmiş planın "planlı" görünmemesi',
    rol: 'uyum yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Toplantı tarihi geçmiş ama yapılmamış', veriHali: 'bayat',
    eylem: 'Gözden geçirme listesine bakar',
    beklenenSonuc: 'Kayıt "gecikmiş plan" olur',
    beklenenEkran: 'Planlı ile gecikmiş plan ayrı işaretlenir',
    beklenenIz: 'yazma yok', beklenenBildirim: 'Görev',
    katmanlar: ['DOMAIN'],
  },
  {
    id: 'DNE-ERS-003', alan: 'Dış denetçi', rota: '/denetci-erisimi',
    eksen: 'akis',
    amac: 'Süresi dolan dış erişimin kendiliğinden kapanması',
    rol: 'sistem (motor)', kapsam: 'kurum geneli',
    onkosul: 'Erişimin bitiş tarihi geçti', veriHali: 'bayat',
    eylem: 'Süre motoru koşar',
    beklenenSonuc: 'Erişim kapanır; kimse elle kapatmayı hatırlamak zorunda kalmaz',
    beklenenEkran: 'Kapanan erişim listede geçmiş olarak durur',
    beklenenIz: 'Erişim · guncelleme', beklenenBildirim: 'yok',
    katmanlar: ['ENGINE', 'WORKFLOW'],
  },
  {
    id: 'MED-KRT-002', alan: 'Taşınabilir medya', rota: '/tasinabilir-medya',
    eksen: 'veri',
    amac: 'Şifrelemesi ölçülmemiş medyanın şifresiz sanılmaması',
    rol: 'güvenlik uzmanı', kapsam: 'kendi tesisi',
    onkosul: 'Şifreleme durumu girilmemiş', veriHali: 'bilinmiyor',
    eylem: 'Medya kaydına bakar',
    beklenenSonuc: 'Şifreleme ÜÇ DEĞERLİDİR; ölçülmemiş `null` kalır',
    beklenenEkran: 'Onaysız kullanım reddedilmez, UYARIYLA kaydedilir',
    beklenenIz: 'Medya · guncelleme', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'DOMAIN'],
  },
  {
    id: 'ESL-MTR-002', alan: 'Eşleştirme', rota: '/eslestirme', eksen: 'veri',
    amac: 'Zayıf bir eşleşmenin güçlü sanılmaması',
    rol: 'uyum uzmanı', kapsam: 'kurum geneli',
    onkosul: 'Denklik "ilgili" düzeyinde', veriHali: 'kısmi',
    eylem: 'Matris hücresine bakar',
    beklenenSonuc: '"İlgili" bir BİLİNMEYEN DEĞİLDİR — zayıf ama kayıtlı bir karardır',
    beklenenEkran: 'Elmas değil planlı işaretçisi alır',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'UI'],
  },
];
