import type { Senaryo } from './tipler';

/* Varlık yönetişimi alanının senaryoları: envanter, zimmet, canlı duruş,
   pasif keşif, sayım, ömür, taşınabilir medya, yedek parça, topoloji,
   konfigürasyon tabanı ve yedekleme.

   Her ekran için mutlu yolun YANINDA en az bir yetki, bir veri hâli ve
   bir arayüz durumu senaryosu vardır: yalnız mutlu yol yazmak, ürünün
   gerçekte nerede kırıldığını ölçmemek demektir. */

export const VARLIK_SENARYOLARI: Senaryo[] = [
  /* ── Envanter · liste ve süzgeç ─────────────────────────────────── */
  {
    id: 'ENV-LST-001', alan: 'Envanter', rota: '/envanter', eksen: 'veri',
    amac: 'Sorumlu olduğum varlıkların bugünkü hâlini tek listede görmek',
    rol: 'BT yöneticisi', kapsam: 'kendi santrali',
    onkosul: 'Kullanıcı giriş yapmış ve en az bir santrale yetkili',
    veriHali: 'normal',
    eylem: 'Envanter ekranını açar',
    beklenenSonuc: 'Yalnız yetkili olduğu santrallerin varlıkları listelenir',
    beklenenEkran: 'Metrik şeridi + tablo; başka santralin kaydı görünmez',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'SCOPE', 'UI'],
  },
  {
    id: 'ENV-LST-002', alan: 'Envanter', rota: '/envanter', eksen: 'veri',
    amac: 'Envanter boşken ne yapmam gerektiğini anlamak',
    rol: 'BT yöneticisi', kapsam: 'kendi santrali',
    onkosul: 'Kapsamda hiç varlık yok', veriHali: 'yok',
    eylem: 'Envanter ekranını açar',
    beklenenSonuc: 'Boş durum, ilk adımı söyleyen bir cümleyle gösterilir',
    beklenenEkran: 'Boş ilk-durum bloğu; sıfır dolu tablo DEĞİL',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'UI'],
  },
  {
    id: 'ENV-LST-003', alan: 'Envanter', rota: '/envanter', eksen: 'veri',
    amac: 'Süzgeç hiçbir kayıt döndürmediğinde çıkış yolunu bulmak',
    rol: 'BT yöneticisi', kapsam: 'kendi santrali',
    onkosul: 'Varlık var ama seçilen mercek hiçbirine uymuyor',
    veriHali: 'kısmi',
    eylem: 'Sonuç vermeyen bir mercek seçer',
    beklenenSonuc: 'Boş süzgeç durumu ve süzgeci temizleme yolu gösterilir',
    beklenenEkran: 'Boş süzgeç bloğu; "kayıt yok" ile "süzgeç boş" ayrı',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'UI'],
  },
  {
    id: 'ENV-LST-004', alan: 'Envanter', rota: '/envanter', eksen: 'veri',
    amac: 'Yüksek satır sayısında ekranın okunur kalması',
    rol: 'BT yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Kapsamda görünür tavandan çok varlık var', veriHali: 'yüksek',
    eylem: 'Envanter ekranını açar',
    beklenenSonuc: 'Sürükleyici satırlar önde kalır, gerisi kuyruğa iner',
    beklenenEkran: 'Görünür satır tavanı aşılmaz; kuyruk sayısı yazılı',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'UI'],
  },
  {
    id: 'ENV-LST-005', alan: 'Envanter', rota: '/envanter', eksen: 'veri',
    amac: 'Ömrü bitmiş ya da bilinmeyen varlığı ayırt etmek',
    rol: 'BT yöneticisi', kapsam: 'kendi santrali',
    onkosul: 'EOS tarihi girilmemiş varlık var', veriHali: 'bilinmiyor',
    eylem: 'Varlık listesine bakar',
    beklenenSonuc: 'Ömrü ölçülmemiş varlık "sağlıklı" sayılmaz',
    beklenenEkran: 'Bilinmeyen işaretçisi; sıfır ya da yeşil DEĞİL',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'UI'],
  },

  /* ── Envanter · yazma ve yetki ──────────────────────────────────── */
  {
    id: 'ENV-YAZ-001', alan: 'Envanter', rota: '/envanter', eksen: 'yetki',
    amac: 'Bir varlığın künyesini düzeltmek',
    rol: 'BT yöneticisi', kapsam: 'kendi santrali',
    onkosul: 'Kullanıcı varlığın santraline yazma yetkili', veriHali: 'normal',
    eylem: 'Varlık formunu açıp bir alanı değiştirir ve kaydeder',
    beklenenSonuc: 'Değişiklik kaydedilir',
    beklenenEkran: 'Çekmece açık kalır, güncel değer görünür',
    beklenenIz: 'Varlik · guncelleme · önceki ve yeni değerle',
    beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'RBAC', 'DOMAIN'],
  },
  {
    id: 'ENV-YAZ-002', alan: 'Envanter', rota: '/envanter', eksen: 'yetki',
    amac: 'Yetkisiz kullanıcının veriyi bozamaması',
    rol: 'salt okuyucu', kapsam: 'kendi santrali',
    onkosul: 'Kullanıcının envanter yazma yetkisi yok', veriHali: 'normal',
    eylem: 'Sunucu eylemini doğrudan çağırmayı dener',
    beklenenSonuc: 'Eylem reddedilir; hiçbir satır değişmez',
    beklenenEkran: 'Yazma yüzeyi hiç açılmaz',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'RBAC'],
  },
  {
    id: 'ENV-YAZ-003', alan: 'Envanter', rota: '/envanter', eksen: 'yetki',
    amac: 'Başka santralin varlığına yazılamaması',
    rol: 'BT yöneticisi', kapsam: 'tek santral',
    onkosul: 'Hedef varlık başka bir santralde', veriHali: 'normal',
    eylem: 'Kapsam dışı varlığın kimliğiyle güncelleme çağırır',
    beklenenSonuc: 'Kapsam kapısı reddeder',
    beklenenEkran: 'Kayıt zaten listede görünmez',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'SCOPE'],
  },
  {
    id: 'ENV-YAZ-004', alan: 'Envanter', rota: '/envanter', eksen: 'akis',
    amac: 'Emekli/imha geçişinin denetimli olması',
    rol: 'BT yöneticisi', kapsam: 'kendi santrali',
    onkosul: 'Kullanıcının onay yetkisi yok', veriHali: 'normal',
    eylem: 'Varlığı emekliye çıkarmayı dener',
    beklenenSonuc: 'Onay yetkisi istenir, geçiş yapılmaz',
    beklenenEkran: 'Yaşam döngüsü formu açılmaz',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'RBAC', 'WORKFLOW'],
  },

  /* ── Envanter · dışa aktarım ────────────────────────────────────── */
  {
    id: 'ENV-DIS-001', alan: 'Envanter', rota: '/envanter', eksen: 'veri',
    amac: 'Listeyi Excel ya da CSV olarak almak',
    rol: 'BT yöneticisi', kapsam: 'kendi santrali',
    onkosul: 'Bir mercek seçili', veriHali: 'normal',
    eylem: 'CSV düğmesine basar',
    beklenenSonuc: 'Dosya, ekranda görünen SÜZÜLMÜŞ kümeyi taşır',
    beklenenEkran: 'İndirme başlar; liste değişmez',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'UI'],
  },
  {
    id: 'ENV-DIS-002', alan: 'Envanter', rota: '/envanter', eksen: 'veri',
    amac: 'Türkçe karakterlerin ve ayraçların dosyada bozulmaması',
    rol: 'BT yöneticisi', kapsam: 'kendi santrali',
    onkosul: 'Kayıtlarda Türkçe karakter, virgül ve tırnak var',
    veriHali: 'normal',
    eylem: 'CSV dışa aktarır',
    beklenenSonuc: 'BOM yazılır, hücreler kaçırılır, satır sonu CRLF olur',
    beklenenEkran: 'Dosya Excel ve LibreOffice\'te aynı okunur',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN'],
  },
  {
    id: 'ENV-DIS-003', alan: 'Envanter', rota: '/envanter', eksen: 'veri',
    amac: 'Dosyayı açan kişinin makinesinde formül çalışmaması',
    rol: 'BT yöneticisi', kapsam: 'kendi santrali',
    onkosul: 'Bir alan "=" ile başlıyor', veriHali: 'kısmi',
    eylem: 'CSV dışa aktarır',
    beklenenSonuc: 'Tehlikeli başlangıç tek tırnakla kaçırılır',
    beklenenEkran: 'Sayı gibi görünen değerler kalkandan muaf',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN'],
  },
  {
    id: 'ENV-DIS-004', alan: 'Envanter', rota: '/envanter', eksen: 'yetki',
    amac: 'Dosyanın kapsam dışına çıkmaması',
    rol: 'BT yöneticisi', kapsam: 'tek santral',
    onkosul: 'Kurumda başka santrallerin varlıkları da var',
    veriHali: 'normal',
    eylem: 'Dışa aktarır',
    beklenenSonuc: 'Dosyada yalnız görmeye yetkili olduğu kayıtlar bulunur',
    beklenenEkran: 'Satır sayısı ekrandaki ile aynı',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'SCOPE'],
  },
  {
    id: 'ENV-DIS-005', alan: 'Envanter', rota: '/envanter', eksen: 'veri',
    amac: 'On bin satırlık dosyanın üretilebilmesi',
    rol: 'kurum yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Çok sayıda kayıt var', veriHali: 'yüksek',
    eylem: 'Dışa aktarır',
    beklenenSonuc: 'Dosya bozulmadan üretilir',
    beklenenEkran: 'İndirme tamamlanır',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN'],
  },

  /* ── Zimmet ─────────────────────────────────────────────────────── */
  {
    id: 'ZIM-ACT-001', alan: 'Zimmet', rota: '/envanter', eksen: 'akis',
    amac: 'Bir cihazı bir kişiye zimmetlemek',
    rol: 'BT yöneticisi', kapsam: 'kendi santrali',
    onkosul: 'Varlığın açık zimmet talebi yok', veriHali: 'normal',
    eylem: 'Sahiplik bloğundan zimmet açar',
    beklenenSonuc: 'Talep açılır; varlığın sahibi HENÜZ DEĞİŞMEZ',
    beklenenEkran: 'Sahiplik alanında "cevap bekliyor" cümlesi',
    beklenenIz: 'VarlikAtamaTalebi · olusturma',
    beklenenBildirim: 'Zimmetlenen kişiye bildirim',
    katmanlar: ['SERVER', 'WORKFLOW', 'DOMAIN'],
  },
  {
    id: 'ZIM-ACT-002', alan: 'Zimmet', rota: '/envanter', eksen: 'akis',
    amac: 'Aynı cihaz için ikinci bir talebin açılmaması',
    rol: 'BT yöneticisi', kapsam: 'kendi santrali',
    onkosul: 'Varlığın zaten bekleyen bir talebi var', veriHali: 'yinelenen',
    eylem: 'İkinci bir zimmet açmayı dener',
    beklenenSonuc: 'Reddedilir; tek aktif talep kuralı korunur',
    beklenenEkran: 'Açık talep gösterilir, yeni form açılmaz',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'WORKFLOW', 'CONCURRENCY'],
  },
  {
    id: 'ZIM-CVP-001', alan: 'Zimmet', rota: '/zimmetlerim', eksen: 'akis',
    amac: 'Bana atanan cihazı kabul etmek',
    rol: 'herhangi bir kullanıcı', kapsam: 'kendi kaydı',
    onkosul: 'Kişinin bekleyen bir talebi var', veriHali: 'normal',
    eylem: 'Kabul eder',
    beklenenSonuc: 'Sahiplik kesinleşir',
    beklenenEkran: 'Talep "kabul ettiklerim" sekmesine geçer',
    beklenenIz: 'İki kayıt: talep durumu + Varlik sahibi',
    beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'WORKFLOW', 'DOMAIN'],
  },
  {
    id: 'ZIM-CVP-002', alan: 'Zimmet', rota: '/zimmetlerim', eksen: 'akis',
    amac: 'Bana ait olmayan cihazı üstlenmemek',
    rol: 'herhangi bir kullanıcı', kapsam: 'kendi kaydı',
    onkosul: 'Kişinin bekleyen bir talebi var', veriHali: 'normal',
    eylem: 'Gerekçe yazıp reddeder',
    beklenenSonuc: 'Sahiplik önceki sahibine döner',
    beklenenEkran: 'Gerekçe yazılmadan red düğmesi açılmaz',
    beklenenIz: 'VarlikAtamaTalebi · red · gerekçeyle',
    beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'WORKFLOW', 'UI'],
  },
  {
    id: 'ZIM-CVP-003', alan: 'Zimmet', rota: '/zimmetlerim', eksen: 'akis',
    amac: 'Redde dönecek sahip yoksa boşluğun görünür kalması',
    rol: 'herhangi bir kullanıcı', kapsam: 'kendi kaydı',
    onkosul: 'Varlığın önceki sahibi yok ya da pasif', veriHali: 'kısmi',
    eylem: 'Reddeder',
    beklenenSonuc: 'Varlık sahipsiz kalır ve veri kalitesi bulgusu açılır',
    beklenenEkran: 'Sahiplik alanı "sahipsiz" der, boş değil',
    beklenenIz: 'Bulgu kaydı açılır',
    beklenenBildirim: 'Veri kalitesi bulgusu',
    katmanlar: ['SERVER', 'WORKFLOW', 'DOMAIN'],
  },
  {
    id: 'ZIM-CVP-004', alan: 'Zimmet', rota: '/zimmetlerim', eksen: 'yetki',
    amac: 'Kimsenin başkası adına kabul edememesi',
    rol: 'BT yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Talep başka bir kişiye ait', veriHali: 'normal',
    eylem: 'Başkasının talebini cevaplamayı dener',
    beklenenSonuc: 'Reddedilir — kimlik kapısı geçilemez',
    beklenenEkran: 'Talep o kişinin ekranında görünmez',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'RBAC', 'WORKFLOW'],
  },
  {
    id: 'ZIM-CVP-005', alan: 'Zimmet', rota: '/envanter', eksen: 'yetki',
    amac: 'Yöneticinin yalnız iptal edebilmesi',
    rol: 'BT yöneticisi', kapsam: 'kendi santrali',
    onkosul: 'Bekleyen bir talep var', veriHali: 'normal',
    eylem: 'Talebi iptal eder',
    beklenenSonuc: 'Talep iptal olur; sahiplik DEĞİŞMEZ',
    beklenenEkran: 'Sahiplik alanı eski sahibi göstermeye devam eder',
    beklenenIz: 'VarlikAtamaTalebi · iptal',
    beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'WORKFLOW'],
  },
  {
    id: 'ZIM-SUR-001', alan: 'Zimmet', rota: '—', eksen: 'akis',
    amac: 'Cevapsız kalan talebin sonsuza kadar beklememesi',
    rol: 'sistem (motor)', kapsam: 'kurum geneli',
    onkosul: 'Talebin son tarihi geçmiş', veriHali: 'bayat',
    eylem: 'Zimmet süresi motoru koşar',
    beklenenSonuc: 'Talep "süresi doldu" olur; KİMSE ADINA KABUL EDİLMEZ',
    beklenenEkran: 'Varlığın sahibi değişmemiş görünür',
    beklenenIz: 'Aktivite kaydı · kaynak: iş koşusu',
    beklenenBildirim: 'Görev açılır',
    katmanlar: ['ENGINE', 'WORKFLOW'],
  },
  {
    id: 'ZIM-SUR-002', alan: 'Zimmet', rota: '—', eksen: 'akis',
    amac: 'Pasifleşen kullanıcının talebinin düşmesi',
    rol: 'sistem (motor)', kapsam: 'kurum geneli',
    onkosul: 'Zimmetlenen kullanıcı pasifleştirilmiş', veriHali: 'kısmi',
    eylem: 'Motor koşar',
    beklenenSonuc: 'Talep iptal olur',
    beklenenEkran: 'Bekleyen listede görünmez',
    beklenenIz: 'Aktivite kaydı', beklenenBildirim: 'Görev',
    katmanlar: ['ENGINE', 'WORKFLOW'],
  },

  /* ── Canlı duruş ────────────────────────────────────────────────── */
  {
    id: 'DUR-TAZ-001', alan: 'Canlı duruş', rota: '/envanter',
    eksen: 'entegrasyon',
    amac: 'Cihazın yamasının güncel olup olmadığını görmek',
    rol: 'BT yöneticisi', kapsam: 'kendi santrali',
    onkosul: 'Kaynak bağlı, son koşu başarılı, veri poll aralığı içinde',
    veriHali: 'normal',
    eylem: 'Varlık çekmecesinde Duruş sekmesini açar',
    beklenenSonuc: 'Alan "CANLI" olarak işaretlenir',
    beklenenEkran: 'Değer, kaynak adı ve yaş birlikte görünür',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'UI'],
  },
  {
    id: 'DUR-TAZ-002', alan: 'Canlı duruş', rota: '/envanter',
    eksen: 'entegrasyon',
    amac: 'Bağlı olmayan kaynağın canlı gösterilmemesi',
    rol: 'BT yöneticisi', kapsam: 'kendi santrali',
    onkosul: 'Hiçbir kaynak sistem bağlı değil', veriHali: 'yok',
    eylem: 'Duruş sekmesini açar',
    beklenenSonuc: '"KAYNAK BAĞLI DEĞİL" yazılır; "canlı" YAZILMAZ',
    beklenenEkran: 'Kusur rengi değil, bekleyen kurulum işaretçisi',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'UI'],
  },
  {
    id: 'DUR-TAZ-003', alan: 'Canlı duruş', rota: '/envanter',
    eksen: 'entegrasyon',
    amac: 'Elle yüklenen verinin akış sanılmaması',
    rol: 'BT yöneticisi', kapsam: 'kendi santrali',
    onkosul: 'Kaynağın sorgu aralığı tanımsız', veriHali: 'kısmi',
    eylem: 'Duruş sekmesini açar',
    beklenenSonuc: 'Tazelik "ölçülmedi" der; canlı sayılmaz',
    beklenenEkran: 'Bilinmeyen işaretçisi',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN'],
  },
  {
    id: 'DUR-TAZ-004', alan: 'Canlı duruş', rota: '/envanter',
    eksen: 'entegrasyon',
    amac: 'Kaynak hata verdiğinde bunun görünmesi',
    rol: 'BT yöneticisi', kapsam: 'kendi santrali',
    onkosul: 'Connector durumu hatalı', veriHali: 'kısmi',
    eylem: 'Duruş sekmesini açar',
    beklenenSonuc: 'Alan "kaynak HATALI" der',
    beklenenEkran: 'Hata işaretçisi ve son hata metni',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'UI'],
  },
  {
    id: 'DUR-CAK-001', alan: 'Canlı duruş', rota: '/envanter', eksen: 'veri',
    amac: 'İki kaynak çeliştiğinde doğru değeri görmek',
    rol: 'BT yöneticisi', kapsam: 'kendi santrali',
    onkosul: 'İki kaynak aynı alan için farklı değer bildirmiş',
    veriHali: 'çelişen',
    eylem: 'Duruş sekmesini açar',
    beklenenSonuc: 'En YENİ ölçüm kazanır; öncelik yalnız berabere bozar',
    beklenenEkran: 'Kaybeden kaynaklar çakışma satırında listelenir',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'UI'],
  },
  {
    id: 'DUR-CAK-002', alan: 'Canlı duruş', rota: '/envanter', eksen: 'veri',
    amac: 'Envanterle sahanın çeliştiğinin söylenmesi',
    rol: 'BT yöneticisi', kapsam: 'kendi santrali',
    onkosul: 'Elle girilen değer ile gözlem farklı', veriHali: 'çelişen',
    eylem: 'Duruş sekmesini açar',
    beklenenSonuc: 'Ürün envanteri KENDİLİĞİNDEN değiştirmez, çelişkiyi yazar',
    beklenenEkran: 'İki değer yan yana + uyarı cümlesi',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'UI'],
  },
  {
    id: 'DUR-API-001', alan: 'Canlı duruş', rota: '—', eksen: 'entegrasyon',
    amac: 'Kaynak sistemin duruş bildirebilmesi',
    rol: 'API istemcisi', kapsam: 'anahtarın kapsamı',
    onkosul: 'Anahtar `asset-state` kapsamı taşıyor', veriHali: 'normal',
    eylem: 'POST /api/v1/asset-state çağırır',
    beklenenSonuc: 'Gözlem yazılır; `Varlik` satırına DOKUNULMAZ',
    beklenenEkran: '—',
    beklenenIz: 'VarlikDurusGozlemi · olusturma + köken kaydı',
    beklenenBildirim: 'yok',
    katmanlar: ['API', 'INTEGRATION'],
  },
  {
    id: 'DUR-API-002', alan: 'Canlı duruş', rota: '—', eksen: 'entegrasyon',
    amac: 'Geç gelen paketin yeni ölçümü geri almaması',
    rol: 'API istemcisi', kapsam: 'anahtarın kapsamı',
    onkosul: 'Gönderilen ölçüm anı kayıttakinden eski', veriHali: 'bayat',
    eylem: 'Eski `observedAt` ile gönderir',
    beklenenSonuc: 'Yazma atlanır ve cevapta `stale` olarak SAYILIR',
    beklenenEkran: '—',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['API', 'INTEGRATION'],
  },
  {
    id: 'DUR-API-003', alan: 'Canlı duruş', rota: '—', eksen: 'yetki',
    amac: 'Kapsam dışı santralin varlığına yazılamaması',
    rol: 'API istemcisi', kapsam: 'tek santral',
    onkosul: 'Hedef varlık başka santralde', veriHali: 'normal',
    eylem: 'Kapsam dışı varlık anahtarıyla gönderir',
    beklenenSonuc: 'Reddedilir; hiçbir gözlem yazılmaz',
    beklenenEkran: '—',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['API', 'SCOPE'],
  },

  /* ── Pasif keşif ────────────────────────────────────────────────── */
  {
    id: 'KES-GRP-001', alan: 'Pasif keşif', rota: '/kesif', eksen: 'veri',
    amac: 'Ağda envanterde olmayan cihazı görmek',
    rol: 'BT yöneticisi', kapsam: 'kendi santrali',
    onkosul: 'Gözlemde eşleşmeyen kayıt var', veriHali: 'normal',
    eylem: 'Keşif ekranını açar',
    beklenenSonuc: 'Kayıt "envanterde yok" grubunda sayılır',
    beklenenEkran: 'Yedi grup özeti; sayıların toplamı kayıt sayısına eşit',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'UI'],
  },
  {
    id: 'KES-GRP-002', alan: 'Pasif keşif', rota: '/kesif', eksen: 'veri',
    amac: 'Sahipsiz cihazın ayrı görünmesi',
    rol: 'BT yöneticisi', kapsam: 'kendi santrali',
    onkosul: 'Eşleşen varlığın sahibi yok', veriHali: 'kısmi',
    eylem: 'Keşif özetine bakar',
    beklenenSonuc: 'Kayıt "sahibi yok" grubuna düşer',
    beklenenEkran: 'Grup tıklanınca liste süzülür',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'UI'],
  },
  {
    id: 'KES-GRP-003', alan: 'Pasif keşif', rota: '/kesif', eksen: 'veri',
    amac: 'Kimliği belirsiz kaydın önce çözülmesi',
    rol: 'BT yöneticisi', kapsam: 'kendi santrali',
    onkosul: 'Kayıt birden çok varlığa uyuyor', veriHali: 'çelişen',
    eylem: 'Keşif özetine bakar',
    beklenenSonuc: 'Kayıt "kimlik çakışması" grubuna düşer ve önceliklidir',
    beklenenEkran: 'Çakışma en üstte; güven skoru "ölçülmedi"',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN'],
  },
  {
    id: 'KES-GRP-004', alan: 'Pasif keşif', rota: '/kesif', eksen: 'veri',
    amac: 'Artık görülmeyen kaydın silinmemesi',
    rol: 'BT yöneticisi', kapsam: 'kendi santrali',
    onkosul: 'Kayıt eşiği aşan süredir görülmemiş', veriHali: 'bayat',
    eylem: 'Keşif özetine bakar',
    beklenenSonuc: 'Kayıt "artık görülmüyor" grubunda; SİLİNMEZ',
    beklenenEkran: 'Eşik konsoldan gelir, koda gömülü değildir',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN'],
  },
  {
    id: 'KES-GRP-005', alan: 'Pasif keşif', rota: '/kesif', eksen: 'yetki',
    amac: 'Santrali bilinmeyen kaydın gizlenmemesi',
    rol: 'BT yöneticisi', kapsam: 'tek santral',
    onkosul: 'Kaydın santrali çözülememiş', veriHali: 'bilinmiyor',
    eylem: 'Keşif ekranını açar',
    beklenenSonuc: 'Kayıt görünür ve "yeri belirsiz" grubuna düşer',
    beklenenEkran: 'Santral süzgecinde ayrı bir seçenek',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'SCOPE'],
  },
  {
    id: 'KES-ESL-001', alan: 'Pasif keşif', rota: '/kesif', eksen: 'veri',
    amac: 'Yanlış cihazın eşleştirilmemesi',
    rol: 'sistem (eşleştirme)', kapsam: 'kurum geneli',
    onkosul: 'Gözlemde yalnız IP var', veriHali: 'kısmi',
    eylem: 'Eşleştirme koşar',
    beklenenSonuc: 'IP TEK BAŞINA eşleşme kurmaz',
    beklenenEkran: 'Kayıt eşleşmemiş kalır',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN'],
  },
  {
    id: 'KES-ONY-001', alan: 'Pasif keşif', rota: '/kesif', eksen: 'akis',
    amac: 'Keşfedilen cihazın kendiliğinden envantere girmemesi',
    rol: 'BT yöneticisi', kapsam: 'kendi santrali',
    onkosul: 'Yüksek güvenli bir eşleşme var', veriHali: 'normal',
    eylem: 'Eşleştirme geçişi koşar',
    beklenenSonuc: 'CMDB\'ye YAZILMAZ; kayıt insan onayı bekler',
    beklenenEkran: 'Beş adımlı tezgâh hattı; karar adımı aktif',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'WORKFLOW'],
  },
  {
    id: 'KES-ONY-002', alan: 'Pasif keşif', rota: '/kesif', eksen: 'yetki',
    amac: 'Kararın yetkili bir kişiye bağlanması',
    rol: 'BT yöneticisi', kapsam: 'kendi santrali',
    onkosul: 'Kullanıcının onay yetkisi yok', veriHali: 'normal',
    eylem: 'Kaydı onaylamayı dener',
    beklenenSonuc: 'Reddedilir',
    beklenenEkran: 'Karar düğmeleri açılmaz',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'RBAC'],
  },
  {
    id: 'KES-YSK-001', alan: 'Pasif keşif', rota: '/kesif', eksen: 'entegrasyon',
    amac: 'Ürünün OT ağına paket atmadığını görmek',
    rol: 'OT mühendisi', kapsam: 'kendi santrali',
    onkosul: '—', veriHali: 'normal',
    eylem: 'Keşif ekranındaki pasiflik bölümünü açar',
    beklenenSonuc: 'Yapılmayan aktif işlemler gerekçeleriyle listelenir',
    beklenenEkran: 'Port tarama · SNMP · Modbus · PLC · aktif paket',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'UI'],
  },
  {
    id: 'KES-YSK-002', alan: 'Pasif keşif', rota: '—', eksen: 'entegrasyon',
    amac: 'Aktif tarama yeteneğinin üründe hiç bulunmaması',
    rol: 'güvenlik denetçisi', kapsam: 'kurum geneli',
    onkosul: '—', veriHali: 'normal',
    eylem: 'Adaptör yetenek kütüğünü inceler',
    beklenenSonuc: 'Kütükte aktif tarama karşılığı bir kod YOKTUR',
    beklenenEkran: '—',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'INTEGRATION'],
  },
];

/* ── İkinci dalga: kalan varlık yüzeyleri ────────────────────────────
   Topoloji, konfigürasyon tabanı, yedekleme, ömür, sayım, taşınabilir
   medya, yedek parça, SBOM, kimlik envanteri ve olay etkisi. */

export const VARLIK_SENARYOLARI_2: Senaryo[] = [
  {
    id: 'ENV-KML-001', alan: 'Envanter', rota: '/envanter', eksen: 'veri',
    amac: 'Bir cihazın künyesinde neyin eksik olduğunu görmek',
    rol: 'BT yöneticisi', kapsam: 'kendi santrali',
    onkosul: 'Bazı kimlik alanları boş', veriHali: 'kısmi',
    eylem: 'Kimlik alanları bloğuna bakar',
    beklenenSonuc: 'Boş alan "ölçülmedi" der; "yok" DEMEZ',
    beklenenEkran: 'Doluluk oranı uygulanamaz alanları paydaya katmaz',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'UI'],
  },
  {
    id: 'ENV-KML-002', alan: 'Envanter', rota: '/envanter', eksen: 'akis',
    amac: 'Bir alanın bu cihaza uygulanmadığını kayda geçirmek',
    rol: 'BT yöneticisi', kapsam: 'kendi santrali',
    onkosul: 'Alan bu cihaz tipinde anlamsız', veriHali: 'kısmi',
    eylem: 'Alanı gerekçesiyle "uygulanamaz" işaretler',
    beklenenSonuc: 'Gerekçesiz işaretleme reddedilir',
    beklenenEkran: 'Alan orandan çıkar, ölçüm borcu sayılmaz',
    beklenenIz: 'Varlik alanı · guncelleme · gerekçeyle',
    beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'DOMAIN'],
  },
  {
    id: 'ENV-YAS-001', alan: 'Envanter', rota: '/envanter',
    eksen: 'entegrasyon',
    amac: 'Cihazdaki yazılım listesini belgeyle almak',
    rol: 'BT yöneticisi', kapsam: 'kendi santrali',
    onkosul: 'SBOM belgesi yüklenmiş', veriHali: 'normal',
    eylem: 'Yazılım listesi bloğunu açar',
    beklenenSonuc: 'Bileşenler ve sürümleri listelenir; sürüm UYDURULMAZ',
    beklenenEkran: 'Okunamayan satır sebebiyle raporlanır, öbürleri kalır',
    beklenenIz: 'SBOM · olusturma', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'SERVER'],
  },
  {
    id: 'ENV-FRM-001', alan: 'Envanter', rota: '/envanter', eksen: 'veri',
    amac: 'Firmware\'in güncel olup olmadığını anlamak',
    rol: 'OT mühendisi', kapsam: 'kendi santrali',
    onkosul: 'Taban sürüm tanımlı değil', veriHali: 'yok',
    eylem: 'Firmware bloğuna bakar',
    beklenenSonuc: 'Taban yoksa UYUMLU sayılmaz',
    beklenenEkran: '"Taban tanımlı değil" ayrı bir durumdur',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN'],
  },
  {
    id: 'ENV-ZAF-001', alan: 'Envanter', rota: '/envanter', eksen: 'veri',
    amac: 'Bir zafiyetin bu cihazı etkileyip etkilemediğini görmek',
    rol: 'güvenlik uzmanı', kapsam: 'kendi santrali',
    onkosul: 'Cihazın SBOM belgesi yok', veriHali: 'bilinmiyor',
    eylem: 'Zafiyet korelasyonuna bakar',
    beklenenSonuc: 'Bileşen zafiyetinden ETKİLENMİŞ sayılmaz',
    beklenenEkran: 'Karar verilemedi; motor insanın kararını ezmez',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['ENGINE', 'DOMAIN'],
  },
  {
    id: 'ENV-AG-001', alan: 'Envanter', rota: '/envanter', eksen: 'veri',
    amac: 'Cihazı doğru ağ segmentine yerleştirmek',
    rol: 'ağ sorumlusu', kapsam: 'kendi santrali',
    onkosul: 'Girilen adres bloğu bozuk', veriHali: 'çelişen',
    eylem: 'Geçersiz bir adres bloğu girer',
    beklenenSonuc: 'Reddedilir',
    beklenenEkran: 'Neyin beklendiği yazılır',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'DOMAIN'],
  },
  {
    id: 'TOP-SAP-001', alan: 'Topoloji', rota: '/topoloji', eksen: 'veri',
    amac: 'Ağda beklenmedik bir değişiklik olup olmadığını görmek',
    rol: 'ağ sorumlusu', kapsam: 'kendi santrali',
    onkosul: 'Onaylı taban anlık yok', veriHali: 'yok',
    eylem: 'Sapma hesabına bakar',
    beklenenSonuc: 'Taban yokken sapma HESAPLANMAZ',
    beklenenEkran: 'İlk anlık kendiliğinden taban olmaz',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['ENGINE', 'DOMAIN'],
  },
  {
    id: 'TOP-SAP-002', alan: 'Topoloji', rota: '/topoloji', eksen: 'akis',
    amac: 'Bir sapmayı karara bağlamak',
    rol: 'ağ sorumlusu', kapsam: 'kendi santrali',
    onkosul: 'Kullanıcının onay yetkisi yok', veriHali: 'normal',
    eylem: 'Sapmayı karara bağlamayı dener',
    beklenenSonuc: 'Reddedilir; sapma AÇIK kalır',
    beklenenEkran: 'Düğme etkinleşmez, gerekçe alanı eşik ister',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'RBAC', 'UI'],
  },
  {
    id: 'TAB-KNF-001', alan: 'Konfigürasyon tabanı', rota: '/tabanlar',
    eksen: 'entegrasyon',
    amac: 'Cihaz konfigürasyonunun onaylı hâlden sapıp sapmadığını görmek',
    rol: 'OT mühendisi', kapsam: 'kendi santrali',
    onkosul: 'Hiç yedek kaydı yok', veriHali: 'yok',
    eylem: 'Sapma durumuna bakar',
    beklenenSonuc: 'Sonuç "bilinmiyor" — "yok" DEĞİL',
    beklenenEkran: 'Kaynak bağlı değilken motor temiz kapanır',
    beklenenIz: 'Koşu kaydı', beklenenBildirim: 'yok',
    katmanlar: ['ENGINE', 'DOMAIN'],
  },
  {
    id: 'YED-POL-001', alan: 'Yedekleme', rota: '/yedekleme', eksen: 'akis',
    amac: 'Yedeğin gerçekten geri yüklenebildiğini kanıtlamak',
    rol: 'BT yöneticisi', kapsam: 'kendi santrali',
    onkosul: 'Politika tanımlı', veriHali: 'normal',
    eylem: 'Geri yükleme testi kaydeder',
    beklenenSonuc: 'Test koşuya bağlanır ve iz bırakır',
    beklenenEkran: 'Testi olmayan yedek "kanıtlanmadı" der',
    beklenenIz: 'Restore testi · olusturma', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'DOMAIN'],
  },
  {
    id: 'YED-POL-002', alan: 'Yedekleme', rota: '/yedekleme', eksen: 'veri',
    amac: 'Bozuk politikanın kaydedilmemesi',
    rol: 'BT yöneticisi', kapsam: 'kendi santrali',
    onkosul: 'Saklama süresi negatif', veriHali: 'çelişen',
    eylem: 'Politikayı kaydetmeyi dener',
    beklenenSonuc: 'Reddedilir',
    beklenenEkran: 'Hata cümlesi alanı adlandırır',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER'],
  },
  {
    id: 'SAY-KMP-001', alan: 'Sayım', rota: '/sayim', eksen: 'akis',
    amac: 'Fiziksel envanter sayımı başlatmak',
    rol: 'BT yöneticisi', kapsam: 'kendi santrali',
    onkosul: 'Kapsamda hiç varlık yok', veriHali: 'yok',
    eylem: 'Sayım açmayı dener',
    beklenenSonuc: 'Açılmaz — sıfır paydalı kampanya olamaz',
    beklenenEkran: 'Neden açılmadığı yazılır',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'DOMAIN'],
  },
  {
    id: 'SAY-KMP-002', alan: 'Sayım', rota: '/sayim', eksen: 'veri',
    amac: 'Sayımda bulunamayan cihazın kaybolmaması',
    rol: 'BT yöneticisi', kapsam: 'kendi santrali',
    onkosul: 'Satır "bulunamadı" işaretlendi', veriHali: 'kısmi',
    eylem: 'Sonucu kaydeder',
    beklenenSonuc: 'Varlık SİLİNMEZ — envanterden düşürme ayrı bir karardır',
    beklenenEkran: '"Sayılmadı" ile "bulunamadı" ayrı durumlardır',
    beklenenIz: 'Sayım satırı · guncelleme', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'WORKFLOW'],
  },
  {
    id: 'MED-KRT-001', alan: 'Taşınabilir medya', rota: '/tasinabilir-medya',
    eksen: 'akis',
    amac: 'Zararlı bulunan medyanın dolaşımdan çıkması',
    rol: 'güvenlik uzmanı', kapsam: 'kendi santrali',
    onkosul: 'Medya zararlı bulundu', veriHali: 'normal',
    eylem: 'Tarama sonucunu kaydeder',
    beklenenSonuc: 'Medya kendiliğinden KARANTİNAYA alınır',
    beklenenEkran: 'Karantinadaki medyaya kullanım kaydı girilemez',
    beklenenIz: 'Medya · guncelleme', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'WORKFLOW'],
  },
  {
    id: 'YDP-STK-001', alan: 'Yedek parça', rota: '/yedek-parca', eksen: 'veri',
    amac: 'Kritik cihaz için yedek parça olup olmadığını görmek',
    rol: 'bakım sorumlusu', kapsam: 'kendi santrali',
    onkosul: 'Tedarik süresi ölçülmemiş', veriHali: 'bilinmiyor',
    eylem: 'Parça kaydına bakar',
    beklenenSonuc: 'Süre BOŞ kalır; sıfır REDDEDİLİR',
    beklenenEkran: 'Kritik varlığa bağlı parçasızlık AÇIK RİSK olur',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'DOMAIN'],
  },
  {
    id: 'OMR-EOL-001', alan: 'Ömür', rota: '/omur', eksen: 'veri',
    amac: 'Ömrü bitecek cihazları önceden görmek',
    rol: 'BT yöneticisi', kapsam: 'kendi santrali',
    onkosul: 'Bazı cihazların EOS tarihi girilmemiş',
    veriHali: 'bilinmiyor',
    eylem: 'Ömür ekranını açar',
    beklenenSonuc: 'Tarihi olmayan cihaz "ömrü bitmedi" sayılmaz',
    beklenenEkran: 'Bilinmeyen ayrı sayılır',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN'],
  },
  {
    id: 'OLY-ETK-001', alan: 'Olay', rota: '/olaylar', eksen: 'veri',
    amac: 'Bir olayın üretime etkisini görmek',
    rol: 'olay sorumlusu', kapsam: 'kendi santrali',
    onkosul: 'Varlığın sistemi tanımlı değil', veriHali: 'kısmi',
    eylem: 'Etki önerisine bakar',
    beklenenSonuc: 'Zincir kopar ve "bilinmiyor" der; "etki yok" DEMEZ',
    beklenenEkran: 'Motor etki alanlarına YAZMAZ, yalnız öneri üretir',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['ENGINE', 'DOMAIN'],
  },
  {
    id: 'OLY-ETK-002', alan: 'Olay', rota: '/olaylar', eksen: 'yetki',
    amac: 'Olayın başka santrale kaçırılmaması',
    rol: 'olay sorumlusu', kapsam: 'tek santral',
    onkosul: 'Olay başka santrale taşınmak isteniyor', veriHali: 'normal',
    eylem: 'Olayın santralini değiştirmeyi dener',
    beklenenSonuc: 'Hedef santralde de yetki aranır ve reddedilir',
    beklenenEkran: 'Santral seçimi kapsamla sınırlı',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'SCOPE'],
  },
  {
    id: 'KES-KYT-001', alan: 'Pasif keşif', rota: '/kesif', eksen: 'akis',
    amac: 'Toplu kararın tek gerekçeyle verilebilmesi',
    rol: 'BT yöneticisi', kapsam: 'kendi santrali',
    onkosul: 'Birden çok kayıt seçili', veriHali: 'yüksek',
    eylem: 'Toplu karar verir',
    beklenenSonuc: 'Hepsi tek gerekçeyle kapanır ve iz TOPLU işaretlenir',
    beklenenEkran: 'Tekrarlanan kimlik iki kez işlenmez',
    beklenenIz: 'Keşif kaydı · karar · toplu',
    beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'WORKFLOW'],
  },
  {
    id: 'KES-KYT-002', alan: 'Pasif keşif', rota: '/kesif',
    eksen: 'entegrasyon',
    amac: 'Kaynak adresinin güvenli olması',
    rol: 'platform yöneticisi', kapsam: 'kurum geneli',
    onkosul: 'Yapılandırmaya bir adres giriliyor', veriHali: 'çelişen',
    eylem: 'Bulut metadata adresi girer',
    beklenenSonuc: 'HER KOŞULDA reddedilir',
    beklenenEkran: 'Düz HTTP de açık izin olmadan reddedilir',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'INTEGRATION'],
  },
  {
    id: 'ZIM-SUR-003', alan: 'Zimmet', rota: '—', eksen: 'akis',
    amac: 'Süre daralınca bir kez uyarılmak',
    rol: 'sistem (motor)', kapsam: 'kurum geneli',
    onkosul: 'Talebin son tarihi yaklaşıyor', veriHali: 'normal',
    eylem: 'Motor iki kez koşar',
    beklenenSonuc: 'Uyarı BİR KEZ üretilir; ikinci koşuda tekrar etmez',
    beklenenEkran: 'Bildirim kutusu gürültüyle dolmaz',
    beklenenIz: 'Aktivite kaydı', beklenenBildirim: 'Görev · bir kez',
    katmanlar: ['ENGINE', 'WORKFLOW'],
  },
];

/* ── Üçüncü dalga: kalan varlık kuralları ───────────────────────────── */

export const VARLIK_SENARYOLARI_3: Senaryo[] = [
  {
    id: 'ENV-ETK-001', alan: 'Envanter', rota: '/envanter', eksen: 'veri',
    amac: 'Bir cihaz dururken ne kaybedeceğimizi bilmek',
    rol: 'santral sorumlusu', kapsam: 'kendi santrali',
    onkosul: 'Varlığın kendi etkisi girilmemiş', veriHali: 'bilinmiyor',
    eylem: 'Üretim etkisine bakar',
    beklenenSonuc: 'Etki proses adımından MİRAS alınır; hiçbiri yoksa BİLİNMİYOR',
    beklenenEkran: '"Yok" ile "bilinmiyor" ayrı yazılır',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN'],
  },
  {
    id: 'ENV-SUR-001', alan: 'Envanter', rota: '/prosesler', eksen: 'veri',
    amac: 'Bir sürecin tek nokta riskini görmek',
    rol: 'süreç sorumlusu', kapsam: 'kendi santrali',
    onkosul: 'Bağın tek noktalığı değerlendirilmemiş', veriHali: 'bilinmiyor',
    eylem: 'Süreç zincirine bakar',
    beklenenSonuc: 'Değerlendirilmemiş bağ TEK NOKTA sayılmaz ama ölçüm borcuna girer',
    beklenenEkran: 'Dört hâl dört ayrı sözle yazılır',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'UI'],
  },
  {
    id: 'KES-ESL-002', alan: 'Pasif keşif', rota: '/kesif', eksen: 'veri',
    amac: 'Aynı cihazın iki kez envantere girmemesi',
    rol: 'sistem (eşleştirme)', kapsam: 'kurum geneli',
    onkosul: 'Gözlem seri numarası taşıyor', veriHali: 'normal',
    eylem: 'Eşleştirme koşar',
    beklenenSonuc: 'Seri numarasıyla eşleşir ve EN YÜKSEK güveni alır',
    beklenenEkran: 'MAC yazımı farkları aynı kabul edilir',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN'],
  },
  {
    id: 'ZIM-KAP-001', alan: 'Zimmet', rota: '/zimmetlerim', eksen: 'akis',
    amac: 'Kapanmış bir talebin yeniden açılmaması',
    rol: 'herhangi bir kullanıcı', kapsam: 'kendi kaydı',
    onkosul: 'Talep zaten cevaplanmış', veriHali: 'yinelenen',
    eylem: 'Aynı talebi tekrar cevaplamayı dener',
    beklenenSonuc: 'Reddedilir',
    beklenenEkran: 'Kapanmış talep bekleyen sekmesinde görünmez',
    beklenenIz: 'yazma yok', beklenenBildirim: 'yok',
    katmanlar: ['DOMAIN', 'WORKFLOW'],
  },
  {
    id: 'ENV-YRS-001', alan: 'Envanter', rota: '/envanter', eksen: 'akis',
    amac: 'İki kişinin aynı anda karar vermesinin veriyi bozmaması',
    rol: 'BT yöneticisi', kapsam: 'kendi santrali',
    onkosul: 'İki onaylayan aynı geçişi aynı anda deniyor',
    veriHali: 'yinelenen',
    eylem: 'Eşzamanlı iki geçiş denenir',
    beklenenSonuc: 'Yalnız biri yazar; kaybeden AÇIK hata alır',
    beklenenEkran: 'İzde TEK satır kalır',
    beklenenIz: 'Tek geçiş satırı', beklenenBildirim: 'yok',
    katmanlar: ['SERVER', 'CONCURRENCY'],
  },
];
